"use client";
import { useCallback, useEffect, useRef, useState } from "react";
type R={id:string;participantRole:string;status:string;duration:string;internalReason:string;participantExplanation:string;proposedAt:string;startsAt:string|null;expiresAt:string|null;canApprove:boolean;proposedByAdministrator:{id:string;name:string|null};events:Array<{id:string;eventType:string;occurredAt:string;reason:string|null;actorAdministrator:{name:string|null}|null}>};
export default function AdminSafetyRestrictions({id}:{id:string}){
 const[rows,setRows]=useState<R[]>([]),[role,setRole]=useState("REPORTER"),[duration,setDuration]=useState("HOURS_24"),[internalReason,setInternal]=useState(""),[explanation,setExplanation]=useState(""),[message,setMessage]=useState(""),[pending,setPending]=useState(false),lock=useRef(false);
 const load=useCallback(()=>fetch(`/api/admin/safety-reports/${id}/restrictions`,{cache:"no-store"}).then(r=>r.json()).then(x=>setRows(x.restrictions??[])),[id]);
 useEffect(()=>{void load()},[load]);
 async function act(url:string,body:object,confirmation:string){if(lock.current||!window.confirm(confirmation))return false;lock.current=true;setPending(true);setMessage("");try{const response=await fetch(url,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),result=await response.json();if(!response.ok){setMessage(`Action failed: ${result.error??"unexpected error"}`);return false}await load();setMessage("Restriction lifecycle updated.");return true}finally{lock.current=false;setPending(false)}}
 async function propose(){if(await act(`/api/admin/safety-reports/${id}/restrictions`,{participantRole:role,duration,internalReason,participantExplanation:explanation},"Create this proposal? It will not activate a restriction.")){setInternal("");setExplanation("")}}
 return <section className="mx-auto mb-8 max-w-3xl rounded-lg border p-4" aria-labelledby="restrictions-heading"><h2 id="restrictions-heading" className="text-xl font-semibold">Temporary account safety restrictions</h2><p className="text-sm">Precautionary controls are not findings or punishment. Proposal does not activate a restriction; approval by a different Administrator is required.</p><div className="mt-4 grid gap-3"><label>Participant side<select className="ml-2 rounded border p-2" value={role} onChange={e=>setRole(e.target.value)} disabled={pending}><option value="REPORTER">Reporter</option><option value="REPORTED_PARTICIPANT">Reported participant</option></select></label><label>Duration<select className="ml-2 rounded border p-2" value={duration} onChange={e=>setDuration(e.target.value)} disabled={pending}><option value="HOURS_24">24 hours</option><option value="DAYS_7">7 days</option><option value="DAYS_30">30 days</option></select></label><label>Internal reason (1–2,000 characters)<textarea className="block min-h-24 w-full rounded border p-2" maxLength={2000} value={internalReason} onChange={e=>setInternal(e.target.value)} disabled={pending}/></label><label>Neutral participant-facing explanation (1–1,000 characters)<textarea className="block min-h-24 w-full rounded border p-2" maxLength={1000} value={explanation} onChange={e=>setExplanation(e.target.value)} disabled={pending}/></label><button className="min-h-11 rounded bg-gray-950 px-4 text-white disabled:opacity-50" disabled={pending} onClick={()=>void propose()}>Confirm proposal creation</button></div>
 {rows.map(r=><article key={r.id} className="mt-5 rounded border p-3"><h3 className="font-semibold">{r.participantRole.replaceAll("_"," ")} · {r.status} · {r.duration.replaceAll("_"," ")}</h3><p><b>Internal reason:</b> {r.internalReason}</p><p><b>Participant explanation:</b> {r.participantExplanation}</p><p>Proposed by {r.proposedByAdministrator.name||"Administrator"} at {new Date(r.proposedAt).toLocaleString()}</p>{r.startsAt&&<p>Effective {new Date(r.startsAt).toLocaleString()} to {new Date(r.expiresAt!).toLocaleString()}</p>}<div className="flex flex-wrap gap-2">{r.status==="PROPOSED"&&<>{r.canApprove?<button disabled={pending} className="rounded border p-2" onClick={()=>void act(`/api/admin/safety-reports/${id}/restrictions/${r.id}/approve`,{},`Approve and activate immediately for ${r.participantRole.replaceAll("_"," ")}?`)}>Approve and activate</button>:<p className="rounded border bg-gray-50 p-2 text-sm" role="note">A different Administrator must approve this proposal.</p>}<button disabled={pending} className="rounded border p-2" onClick={()=>{const reason=window.prompt("Internal rejection reason");if(reason)void act(`/api/admin/safety-reports/${id}/restrictions/${r.id}/reject`,{reason},"Reject this proposal?")}}>Reject proposal</button></>}{r.status==="ACTIVE"&&<button disabled={pending} className="rounded border p-2" onClick={()=>{const reason=window.prompt("Internal reversal reason");if(reason)void act(`/api/admin/safety-reports/${id}/restrictions/${r.id}/reverse`,{reason},"Reverse this active restriction immediately?")}}>Reverse active restriction</button>}</div><h4 className="mt-2 font-medium">Append-only event history</h4><ol>{r.events.map(e=><li key={e.id}>{new Date(e.occurredAt).toLocaleString()} · {e.eventType} · {e.actorAdministrator?.name||"System"}{e.reason?` · ${e.reason}`:""}</li>)}</ol></article>)}<p role="status" aria-live="polite">{message}</p></section>;
}
