"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { applicantName, createAdminOperatorApplicationController, safeSupportingUrl, validateReview, type AdminApplication, type ReviewDecision } from "@/lib/admin-operator-application-ui";
function date(value:string|null){return value?new Intl.DateTimeFormat(undefined,{dateStyle:"medium"}).format(new Date(value)):"—"}
export default function AdminOperatorApplicationDetail({id}:{id:string}){
 const controller=useMemo(()=>createAdminOperatorApplicationController(fetch),[]); const [application,setApplication]=useState<AdminApplication|null>(null); const [state,setState]=useState<"loading"|"ready"|"missing"|"failed">("loading"); const [message,setMessage]=useState(""); const [decision,setDecision]=useState<ReviewDecision|"">(""); const [reviewNote,setReviewNote]=useState(""); const [errors,setErrors]=useState<{decision?:string;reviewNote?:string}>({}); const [confirm,setConfirm]=useState(false); const [submitting,setSubmitting]=useState(false); const dialog=useRef<HTMLDivElement>(null); const confirmButton=useRef<HTMLButtonElement>(null); const returnFocus=useRef<HTMLButtonElement|null>(null);
 const load=useCallback(async()=>{setState("loading");const outcome=await controller.detail(id);if(outcome.kind==="error"){setMessage(outcome.message);setState(outcome.status===404?"missing":"failed");return;}setApplication(outcome.value);setState("ready");},[controller,id]); useEffect(()=>{void load()},[load]); useEffect(()=>{if(confirm)confirmButton.current?.focus();else returnFocus.current?.focus()},[confirm]);
 function requestConfirmation(event:React.FormEvent){event.preventDefault();const next=validateReview(decision,reviewNote);setErrors(next);if(Object.keys(next).length){setMessage("Check the highlighted review fields.");return;}returnFocus.current=document.activeElement instanceof HTMLButtonElement?document.activeElement:null;setConfirm(true)}
 async function submit(){if(!decision||submitting)return;setSubmitting(true);setMessage("");const outcome=await controller.review(id,decision,reviewNote,load,async()=>{});setSubmitting(false);setMessage(outcome.message);if(outcome.kind==="success"){setConfirm(false);setDecision("");setReviewNote("");setErrors({});}}
 if(state==="loading")return <main className="mx-auto max-w-4xl px-4 py-10"><p role="status">Loading application…</p></main>; if(state==="missing")return <main className="mx-auto max-w-4xl px-4 py-10"><p role="alert">{message}</p><Link href="/admin/operator-applications" className="mt-4 inline-block underline">Return to applications</Link></main>; if(state==="failed"||!application)return <main className="mx-auto max-w-4xl px-4 py-10"><p role="alert">{message}</p><button onClick={()=>void load()} className="mt-4 min-h-11 rounded-lg border px-4">Try again</button></main>;
 const url=safeSupportingUrl(application.supportingUrl); return <main className="mx-auto max-w-4xl px-4 py-10"><Link href="/admin/operator-applications" className="underline">← Application queue</Link><div className="mt-5 flex flex-wrap justify-between gap-3"><div><h1 className="text-3xl font-bold text-spartan-green">{applicantName(application)}</h1><p className="text-gray-600">Operator application detail</p></div><span className="rounded-full border px-3 py-2 font-semibold">Status: {application.status}</span></div>{message&&<p className="mt-5 rounded-lg border p-3" role="alert" aria-live="assertive">{message}</p>}<dl className="mt-6 grid gap-3 rounded-xl border bg-white p-5 sm:grid-cols-3"><div><dt className="font-medium">Submitted</dt><dd>{date(application.submittedAt)}</dd></div><div><dt className="font-medium">Reviewed</dt><dd>{date(application.reviewedAt)}</dd></div><div><dt className="font-medium">Withdrawn</dt><dd>{date(application.withdrawnAt)}</dd></div>{application.reviewer&&<div><dt className="font-medium">Reviewer</dt><dd>{application.reviewer.name||"Administrator"}</dd></div>}</dl><section className="mt-6 space-y-5 rounded-xl border bg-white p-5" aria-labelledby="application-content"><h2 id="application-content" className="text-xl font-semibold">Application content</h2><Text title="Qualifications" value={application.qualifications}/><Text title="Relevant experience" value={application.relevantExperience}/><Text title="Languages" value={application.languages.join(", ")}/><Text title="Availability" value={application.availability}/><Text title="Additional note" value={application.additionalNote||"Not provided"}/>{url?<p><span className="block font-medium">Supporting information</span><a href={url} target="_blank" rel="noopener noreferrer" className="text-spartan-green underline">Open supporting URL <span className="sr-only">(opens in a new tab)</span></a></p>:<Text title="Supporting information" value="Not provided"/>}{application.reviewNote&&<Text title="Administrator review feedback" value={application.reviewNote}/>}</section>
 {application.status==="PENDING"&&<section className="mt-6 rounded-xl border bg-white p-5" aria-labelledby="review-heading"><h2 id="review-heading" className="text-xl font-semibold">Review application</h2><form className="mt-4 space-y-4" onSubmit={requestConfirmation} noValidate><fieldset aria-describedby="decision-error"><legend className="font-medium">Decision</legend><label className="mt-2 flex min-h-11 items-center gap-3"><input type="radio" name="decision" value="APPROVED" checked={decision==="APPROVED"} disabled={submitting} onChange={()=>{setDecision("APPROVED");setErrors(e=>({...e,decision:undefined}))}}/>Approve</label><label className="flex min-h-11 items-center gap-3"><input type="radio" name="decision" value="REJECTED" checked={decision==="REJECTED"} disabled={submitting} onChange={()=>{setDecision("REJECTED");setErrors(e=>({...e,decision:undefined}))}}/>Reject</label>{errors.decision&&<p id="decision-error" className="text-sm text-red-700">{errors.decision}</p>}</fieldset><div><label htmlFor="review-note" className="font-medium">Administrator feedback (optional)</label><textarea id="review-note" value={reviewNote} maxLength={1000} disabled={submitting} aria-invalid={Boolean(errors.reviewNote)} aria-describedby="review-note-help review-note-error" onChange={e=>{setReviewNote(e.target.value);setErrors(v=>({...v,reviewNote:undefined}))}} rows={5} className="mt-1 w-full rounded-lg border p-3"/><p id="review-note-help" className="text-xs text-gray-500">{reviewNote.length}/1,000 characters</p>{errors.reviewNote&&<p id="review-note-error" className="text-sm text-red-700">{errors.reviewNote}</p>}</div><button type="submit" disabled={submitting} className="min-h-11 rounded-lg bg-spartan-green px-5 font-semibold text-white disabled:opacity-50">Review decision</button></form></section>}
 {confirm&&decision&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" onMouseDown={e=>{if(e.target===e.currentTarget&&!submitting)setConfirm(false)}}><div ref={dialog} role="dialog" aria-modal="true" aria-labelledby="confirm-review-title" aria-describedby="confirm-review-description" className="w-full max-w-md rounded-xl bg-white p-6" onKeyDown={e=>{if(e.key==="Escape"&&!submitting)setConfirm(false);if(e.key==="Tab"){const controls=[...(dialog.current?.querySelectorAll<HTMLElement>("button:not(:disabled)")??[])];if(!controls.length)return;const index=controls.indexOf(document.activeElement as HTMLElement);const next=e.shiftKey?(index<=0?controls.length-1:index-1):(index>=controls.length-1?0:index+1);e.preventDefault();controls[next].focus()}}}><h2 id="confirm-review-title" className="text-xl font-semibold">Confirm {decision==="APPROVED"?"approval":"rejection"}</h2><p id="confirm-review-description" className="mt-2 text-gray-700">{decision==="APPROVED"?`Approving ${applicantName(application)} changes their role to OPERATOR. Their Operator profile remains in pilot status PENDING and they are not automatically activated for assignments.`:`Rejecting ${applicantName(application)} does not change their Viewer role.`}</p><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button type="button" disabled={submitting} onClick={()=>setConfirm(false)} className="min-h-11 rounded-lg border px-4">Cancel</button><button ref={confirmButton} type="button" disabled={submitting} onClick={()=>void submit()} className="min-h-11 rounded-lg bg-spartan-green px-4 font-semibold text-white disabled:opacity-50">{submitting?"Submitting…":`Confirm ${decision==="APPROVED"?"approval":"rejection"}`}</button></div></div></div>}
 </main>
}
function Text({title,value}:{title:string;value:string}){return <div><h3 className="font-medium">{title}</h3><p className="mt-1 whitespace-pre-wrap text-gray-700">{value}</p></div>}
