"use client";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ADMIN_APPLICATION_STATUSES, applicantName, createAdminOperatorApplicationController, normalizeQueueState, statusDate, type AdminApplication, type AdminStatusFilter } from "@/lib/admin-operator-application-ui";
function date(value: string) { return new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)); }
export default function AdminOperatorApplications() {
 const controller = useMemo(() => createAdminOperatorApplicationController(fetch), []); const [status, setStatus] = useState<AdminStatusFilter>("ALL"); const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(20); const [items, setItems] = useState<AdminApplication[]>([]); const [hasNext, setHasNext] = useState(false); const [state, setState] = useState<"loading"|"ready"|"failed"|"unauthorized">("loading"); const [message, setMessage] = useState("");
 const load = useCallback(async () => { const normalized = normalizeQueueState(status,page,pageSize); if(normalized.page!==page)setPage(normalized.page); setState("loading"); const outcome=await controller.queue(normalized.status,normalized.page,normalized.pageSize); if(outcome.kind==="error"){setMessage(outcome.message);setState(outcome.status===401||outcome.status===403?"unauthorized":"failed");return;} setItems(outcome.value.applications);setHasNext(outcome.value.hasNext);setState("ready"); },[controller,page,pageSize,status]); useEffect(()=>{void load();},[load]);
 return <main className="mx-auto max-w-5xl px-4 py-10"><h1 className="text-3xl font-bold text-spartan-green">Operator applications</h1><p className="mt-2 text-gray-600">Review Viewer applications without making assumptions about suitability or review timing.</p><div className="mt-6 flex flex-wrap items-end gap-4 rounded-xl border bg-white p-4"><div><label htmlFor="application-status" className="block text-sm font-medium">Application status</label><select id="application-status" value={status} onChange={e=>{setStatus(e.target.value as AdminStatusFilter);setPage(1);}} className="mt-1 min-h-11 rounded-lg border px-3">{ADMIN_APPLICATION_STATUSES.map(v=><option key={v} value={v}>{v==="ALL"?"All statuses":v[0]+v.slice(1).toLowerCase()}</option>)}</select></div><div><label htmlFor="application-page-size" className="block text-sm font-medium">Applications per page</label><select id="application-page-size" value={pageSize} onChange={e=>{setPageSize(Number(e.target.value));setPage(1);}} className="mt-1 min-h-11 rounded-lg border px-3"><option value="10">10</option><option value="20">20</option><option value="50">50</option></select></div><button type="button" onClick={()=>void load()} className="min-h-11 rounded-lg border px-4 focus-visible:ring-2">Refresh</button></div><div aria-live="polite">{state==="loading"&&<p className="mt-6" role="status">Loading applications…</p>}{state==="unauthorized"&&<p className="mt-6 rounded-lg bg-red-50 p-4" role="alert">Administrator access is required.</p>}{state==="failed"&&<p className="mt-6 rounded-lg bg-red-50 p-4" role="alert">{message}</p>}</div>{state==="ready"&&(items.length===0?<p className="mt-6 rounded-xl border bg-white p-5">{status==="ALL"?"No Operator applications have been submitted.":`No ${status.toLowerCase()} applications match this filter.`}</p>:<ul className="mt-6 grid gap-4">{items.map(item=><QueueCard key={item.id} application={item}/>)}</ul>)}{state==="ready"&&<nav aria-label="Application queue pages" className="mt-6 flex items-center justify-between"><button type="button" disabled={page===1} onClick={()=>setPage(v=>Math.max(1,v-1))} className="min-h-11 rounded-lg border px-4 disabled:opacity-50">Previous</button><span>Page {page}</span><button type="button" disabled={!hasNext} onClick={()=>setPage(v=>v+1)} className="min-h-11 rounded-lg border px-4 disabled:opacity-50">Next</button></nav>}</main>;
}
function QueueCard({application}:{application:AdminApplication}){return <li className="rounded-xl border bg-white p-5"><div className="flex flex-wrap justify-between gap-2"><div><h2 className="font-semibold">{applicantName(application)}</h2><p className="text-sm text-gray-600">Applicant role: {application.applicant?.role??"Unavailable"}</p></div><span className="rounded-full border px-3 py-1 text-sm font-semibold">Status: {application.status[0]+application.status.slice(1).toLowerCase()}</span></div><dl className="mt-3 grid gap-2 text-sm sm:grid-cols-3"><div><dt className="font-medium">Submitted</dt><dd>{date(application.submittedAt)}</dd></div><div><dt className="font-medium">Latest lifecycle date</dt><dd>{date(statusDate(application))}</dd></div>{application.reviewer&&<div><dt className="font-medium">Reviewed by</dt><dd>{application.reviewer.name||"Administrator"}</dd></div>}</dl><Link href={`/admin/operator-applications/${application.id}`} className="mt-4 inline-flex min-h-11 items-center rounded-lg border px-4 font-semibold text-spartan-green focus-visible:ring-2">View application details</Link></li>}
