"use client";
import Link from "next/link";
import { useEffect, useState } from "react";

type Item={id:string;tripId:string;category:string;severity:string;createdAt:string;reporterRole:string;reportedRole:string;reporter:{id:string;name:string|null};reported:{id:string;name:string|null}};
const categories=["","HARASSMENT","DISCRIMINATION","THREATENING_BEHAVIOR","UNSAFE_CONDUCT","PROPERTY_OR_PRIVACY_CONCERN","OTHER"],severities=["","LOW","MEDIUM","HIGH","CRITICAL"];
const label=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/^./,c=>c.toUpperCase());

export default function AdminSafetyReports(){const[items,setItems]=useState<Item[]>([]),[category,setCategory]=useState(""),[severity,setSeverity]=useState(""),[cursor,setCursor]=useState<string|null>(null),[next,setNext]=useState<string|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{const request=new AbortController(),query=new URLSearchParams({limit:"20"});if(category)query.set("category",category);if(severity)query.set("severity",severity);if(cursor)query.set("cursor",cursor);setLoading(true);setError("");fetch(`/api/admin/safety-reports?${query}`,{cache:"no-store",signal:request.signal}).then(async response=>{if(!response.ok)throw new Error();return response.json()}).then(data=>{setItems(data.items);setNext(data.nextCursor)}).catch(value=>{if(value?.name!=="AbortError")setError("Safety reports could not be loaded.")}).finally(()=>setLoading(false));return()=>request.abort()},[category,severity,cursor]);
  function resetFilters(setter:(value:string)=>void,value:string){setter(value);setCursor(null)}
  return <main className="mx-auto max-w-5xl px-4 py-8"><h1 className="text-3xl font-bold">Safety Reports</h1><div className="mt-3 rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm"><p className="font-semibold">Confidential participant-submitted information</p><p>Access is restricted to authorized Administrators. A submitted concern is not itself a factual determination. Do not share this information outside authorized operational processes.</p></div><div className="mt-6 flex flex-wrap gap-4"><label>Category <select value={category} onChange={e=>resetFilters(setCategory,e.target.value)} className="ml-2 min-h-11 rounded border px-2">{categories.map(value=><option key={value} value={value}>{value?label(value):"All categories"}</option>)}</select></label><label>Severity <select value={severity} onChange={e=>resetFilters(setSeverity,e.target.value)} className="ml-2 min-h-11 rounded border px-2">{severities.map(value=><option key={value} value={value}>{value?label(value):"All severities"}</option>)}</select></label></div>{loading?<p className="mt-6" role="status">Loading confidential reports…</p>:error?<p className="mt-6 text-red-700" role="alert">{error}</p>:items.length===0?<p className="mt-6">No submitted reports match these filters.</p>:<div className="mt-6 overflow-x-auto"><table className="w-full min-w-[760px] border-collapse text-left text-sm"><thead><tr className="border-b"><th className="p-3">Submitted</th><th className="p-3">Concern</th><th className="p-3">Journey</th><th className="p-3">Reporter</th><th className="p-3">Reported participant</th><th className="p-3">Review</th></tr></thead><tbody>{items.map(item=><tr key={item.id} className="border-b"><td className="p-3">{new Date(item.createdAt).toLocaleString()}</td><td className="p-3">{label(item.category)} · {label(item.severity)}</td><td className="p-3 font-mono text-xs">{item.tripId}</td><td className="p-3">{item.reporter.name||"Unnamed participant"} ({label(item.reporterRole)})</td><td className="p-3">{item.reported.name||"Unnamed participant"} ({label(item.reportedRole)})</td><td className="p-3"><Link className="underline focus-visible:ring-2" href={`/admin/safety-reports/${item.id}`}>View submitted report</Link></td></tr>)}</tbody></table></div>}<div className="mt-6 flex gap-3">{cursor&&<button className="min-h-11 rounded border px-4" onClick={()=>setCursor(null)}>First page</button>}{next&&<button className="min-h-11 rounded border px-4" onClick={()=>setCursor(next)}>Next page</button>}</div></main>}
