"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";
import { Button, Field, MetadataList, Notice, Select, StatePanel, StatusBadge, Surface, TextArea } from "@/components/ui/primitives";

type Occurrence = { id: string; status: string; availabilityStart: string; availabilityEnd: string; _count: { claims: number } };
type Item = { id: string; status: string; version: number; publicPlaceName: string; coarseLocation: string; durationMinutes: number; priceMinor: number; currency: string; guidedExperience: { title: string; description: string; occurrences: Occurrence[] } };
type Form = { title: string; description: string; publicPlaceName: string; coarseLocation: string; durationMinutes: number; priceMinor: number; currency: string };
type Feedback = { kind: "success" | "error"; text: string } | null;
type OccurrenceEditor = { itemId: string; occurrenceId: string; mode: "edit" | "replace"; value: string } | null;
const initial: Form = { title: "", description: "", publicPlaceName: "", coarseLocation: "", durationMinutes: 60, priceMinor: 2500, currency: "USD" };
const localIso = (value: string) => new Date(value).toISOString();
const toLocal = (value: string) => { const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60000).toISOString().slice(0, 16); };

function ExperienceFields({ prefix, form, setForm }: { prefix: string; form: Form; setForm: (form: Form) => void }) {
  return <div className="grid gap-5 sm:grid-cols-2"><Field id={`${prefix}-title`} label="Title"><input required minLength={3} maxLength={120} value={form.title} onChange={event => setForm({ ...form, title: event.target.value })} className="unfar-control" /></Field><div className="sm:col-span-2"><Field id={`${prefix}-description`} label="Description"><TextArea required minLength={20} maxLength={2000} value={form.description} onChange={event => setForm({ ...form, description: event.target.value })} /></Field></div><Field id={`${prefix}-place`} label="Public place"><input required maxLength={120} value={form.publicPlaceName} onChange={event => setForm({ ...form, publicPlaceName: event.target.value })} className="unfar-control" /></Field><Field id={`${prefix}-location`} label="Coarse location"><input required maxLength={120} value={form.coarseLocation} onChange={event => setForm({ ...form, coarseLocation: event.target.value })} className="unfar-control" /></Field><Field id={`${prefix}-duration`} label="Duration in minutes"><input required type="number" min="1" max="1440" value={form.durationMinutes} onChange={event => setForm({ ...form, durationMinutes: Number(event.target.value) })} className="unfar-control" /></Field><Field id={`${prefix}-price`} label="Price in minor units"><input required type="number" min="1" value={form.priceMinor} onChange={event => setForm({ ...form, priceMinor: Number(event.target.value) })} className="unfar-control" /></Field><Field id={`${prefix}-currency`} label="Currency"><Select value={form.currency} onChange={event => setForm({ ...form, currency: event.target.value })}><option>USD</option><option>EUR</option><option>GBP</option><option>CAD</option><option>BRL</option></Select></Field></div>;
}

export default function GuidedExperienceManager() {
  const [items, setItems] = useState<Item[]>([]), [form, setForm] = useState(initial), [start, setStart] = useState(""), [selected, setSelected] = useState("");
  const [loadState, setLoadState] = useState<"loading" | "ready" | "error">("loading"), [feedback, setFeedback] = useState<Feedback>(null), [pending, setPending] = useState("");
  const [editingId, setEditingId] = useState<string | null>(null), [editForm, setEditForm] = useState<Form>(initial), [occurrenceEditor, setOccurrenceEditor] = useState<OccurrenceEditor>(null);
  const load = useCallback(async () => { setLoadState("loading"); try { const response = await fetch("/api/operator/guided-experiences", { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Guided Experiences could not be loaded."); setItems(data.guidedExperiences ?? []); setLoadState("ready"); } catch (value) { setFeedback({ kind: "error", text: value instanceof Error ? value.message : "Guided Experiences could not be loaded." }); setLoadState("error"); } }, []);
  useEffect(() => { void load(); }, [load]);

  async function mutate(key: string, url: string, body: unknown, method = "POST", success = "Guided Experience updated.") { if (pending) return false; setPending(key); setFeedback(null); try { const response = await fetch(url, { method, headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); if (!response.ok) throw new Error(data.error ?? "Unable to update Guided Experience"); await load(); setFeedback({ kind: "success", text: success }); return true; } catch (value) { setFeedback({ kind: "error", text: value instanceof Error ? value.message : "Unable to update Guided Experience" }); return false; } finally { setPending(""); } }
  async function create(event: FormEvent) { event.preventDefault(); if (await mutate("create", "/api/operator/guided-experiences", form, "POST", "Guided Experience draft created.")) setForm(initial); }
  async function occurrence(event: FormEvent) { event.preventDefault(); if (!selected || !start) return; if (await mutate("occurrence:create", `/api/operator/guided-experiences/${selected}/occurrences`, { startAt: localIso(start), replacesOccurrenceId: null }, "POST", "Occurrence draft added.")) setStart(""); }
  function beginEdit(item: Item) { setOccurrenceEditor(null); setEditingId(item.id); setEditForm({ title: item.guidedExperience.title, description: item.guidedExperience.description, publicPlaceName: item.publicPlaceName, coarseLocation: item.coarseLocation, durationMinutes: item.durationMinutes, priceMinor: item.priceMinor, currency: item.currency }); setFeedback(null); }
  async function saveEdit(event: FormEvent, item: Item) { event.preventDefault(); if (await mutate(`listing:${item.id}:edit`, `/api/operator/guided-experiences/${item.id}`, { expectedVersion: item.version, ...editForm }, "PATCH", "Guided Experience changes saved.")) setEditingId(null); }
  async function submitOccurrenceEditor(event: FormEvent, item: Item, occurrence: Occurrence) { event.preventDefault(); if (!occurrenceEditor?.value) return; const edit = occurrenceEditor.mode === "edit"; const ok = await mutate(`occurrence:${occurrence.id}:${occurrenceEditor.mode}`, edit ? `/api/operator/guided-experiences/${item.id}/occurrences/${occurrence.id}` : `/api/operator/guided-experiences/${item.id}/occurrences/${occurrence.id}/replace`, edit ? { expectedStartAt: occurrence.availabilityStart, startAt: localIso(occurrenceEditor.value) } : { startAt: localIso(occurrenceEditor.value) }, edit ? "PATCH" : "POST", edit ? "Occurrence start updated." : "Occurrence archived and replacement created."); if (ok) setOccurrenceEditor(null); }
  const lifecycle = (item: Item, action: string) => void mutate(`listing:${item.id}:${action}`, `/api/operator/guided-experiences/${item.id}/${action}`, { expectedVersion: item.version }, "POST", `Guided Experience ${action} succeeded.`);
  const occurrenceAction = (item: Item, occurrence: Occurrence, action: string, method = "POST") => void mutate(`occurrence:${occurrence.id}:${action}`, `/api/operator/guided-experiences/${item.id}/occurrences/${occurrence.id}${action ? `/${action}` : ""}`, {}, method, `Occurrence ${action || "deletion"} succeeded.`);

  return <section aria-labelledby="guided-manager-title" className="mt-12"><h2 id="guided-manager-title" className="text-heading-2">Guided Experiences</h2><p className="mt-2 text-body-sm text-ink-secondary">Create reusable descriptions and explicit one-time occurrences. Times are entered locally and stored as absolute instants. No recurrence is generated.</p>
    <Surface className="mt-5"><h3 className="text-heading-3">Create Guided Experience</h3><form onSubmit={create} className="mt-5"><ExperienceFields prefix="guided-create" form={form} setForm={setForm} /><Button className="mt-5 w-full sm:w-auto" type="submit" disabled={Boolean(pending)}>{pending === "create" ? "Creating draft…" : "Create draft"}</Button></form></Surface>
    <Surface className="mt-5"><h3 className="text-heading-3">Add one-time occurrence</h3><p className="mt-2 text-body-sm text-ink-secondary">The server derives the occurrence end from the listing duration. No recurring schedule is created.</p><form onSubmit={occurrence} className="mt-5 grid gap-5 sm:grid-cols-2"><Field id="occurrence-listing" label="Guided Experience"><Select required value={selected} onChange={event => setSelected(event.target.value)}><option value="">Choose a draft or published listing</option>{items.filter(item => item.status !== "ARCHIVED").map(item => <option key={item.id} value={item.id}>{item.guidedExperience.title}</option>)}</Select></Field><Field id="occurrence-start" label="One-time occurrence start" description="Your device-local time is converted to an absolute timestamp."><input required type="datetime-local" value={start} onChange={event => setStart(event.target.value)} className="unfar-control" /></Field><Button className="sm:col-span-2 sm:w-fit" type="submit" disabled={Boolean(pending) || !selected}>{pending === "occurrence:create" ? "Adding occurrence…" : "Add occurrence draft"}</Button></form></Surface>
    {feedback && <Notice className="mt-4" variant={feedback.kind === "error" ? "danger" : "success"} role={feedback.kind === "error" ? "alert" : "status"}><p>{feedback.text}</p></Notice>}
    <section className="mt-7" aria-labelledby="existing-guided"><h3 id="existing-guided" className="text-heading-3">Existing Guided Experiences</h3>{loadState === "loading" && <StatePanel title="Loading Guided Experiences" busy><p role="status">Loading listings and occurrences…</p></StatePanel>}{loadState === "error" && <StatePanel title="Guided Experiences could not be loaded" tone="danger" action={<Button variant="secondary" onClick={() => void load()}>Retry</Button>}><p role="alert">Existing successfully loaded listings remain unchanged.</p></StatePanel>}{loadState === "ready" && items.length === 0 && <StatePanel title="No Guided Experiences yet"><p>Create a draft to begin managing reusable listings.</p></StatePanel>}
      {items.length > 0 && <ul className="mt-4 grid gap-5">{items.map(item => <li key={item.id}><Surface><div className="flex min-w-0 flex-wrap justify-between gap-3"><div className="min-w-0"><h4 className="break-words text-heading-3">{item.guidedExperience.title}</h4><p className="mt-1 break-words text-body-sm text-ink-secondary">{item.publicPlaceName} · {item.coarseLocation}</p></div><StatusBadge>{item.status}</StatusBadge></div><p className="mt-4 whitespace-pre-wrap break-words text-body-sm">{item.guidedExperience.description}</p><MetadataList className="mt-4" items={[{ term: "Duration", detail: `${item.durationMinutes} minutes` }, { term: "Compensation", detail: `${(item.priceMinor / 100).toFixed(2)} ${item.currency} (${item.priceMinor} minor units)` }]} />
        {editingId === item.id ? <form onSubmit={event => void saveEdit(event, item)} className="mt-5 rounded-lg border border-line bg-surface-subtle p-4"><h5 className="text-label">Edit Guided Experience template</h5><div className="mt-4"><ExperienceFields prefix={`guided-edit-${item.id}`} form={editForm} setForm={setEditForm} /></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><Button type="submit" disabled={Boolean(pending)}>{pending === `listing:${item.id}:edit` ? "Saving…" : "Save changes"}</Button><Button variant="secondary" disabled={Boolean(pending)} onClick={() => setEditingId(null)}>Cancel</Button></div></form> : <div className="mt-5 flex flex-col gap-3 sm:flex-row sm:flex-wrap">{(item.status === "DRAFT" || item.status === "PAUSED") && <Button variant="secondary" disabled={Boolean(pending)} onClick={() => beginEdit(item)}>Edit template</Button>}{item.status === "DRAFT" && <Button variant="secondary" disabled={Boolean(pending)} onClick={() => lifecycle(item, "publish")}>{pending === `listing:${item.id}:publish` ? "Publishing…" : "Publish listing"}</Button>}{item.status === "PUBLISHED" && <Button variant="secondary" disabled={Boolean(pending)} onClick={() => lifecycle(item, "pause")}>{pending === `listing:${item.id}:pause` ? "Pausing…" : "Pause"}</Button>}{item.status === "PAUSED" && <Button variant="secondary" disabled={Boolean(pending)} onClick={() => lifecycle(item, "resume")}>{pending === `listing:${item.id}:resume` ? "Resuming…" : "Resume"}</Button>}{item.status !== "ARCHIVED" && <Button variant="danger" disabled={Boolean(pending)} onClick={() => lifecycle(item, "archive")}>{pending === `listing:${item.id}:archive` ? "Archiving…" : "Archive listing"}</Button>}</div>}
        <section className="mt-6 border-t border-line pt-5" aria-labelledby={`occurrences-${item.id}`}><h5 id={`occurrences-${item.id}`} className="text-label">Occurrences</h5>{item.guidedExperience.occurrences.length === 0 ? <p className="mt-2 text-body-sm text-ink-secondary">No occurrences yet.</p> : <ul className="mt-3 grid gap-3">{item.guidedExperience.occurrences.map(occurrence => <li key={occurrence.id} className="rounded-lg border border-line bg-surface-subtle p-4"><div className="flex flex-wrap justify-between gap-2"><StatusBadge>{occurrence.status}</StatusBadge><span className="text-body-sm">Claims/history: {occurrence._count.claims}</span></div><p className="mt-3 break-words text-body-sm">{new Date(occurrence.availabilityStart).toLocaleString()} – {new Date(occurrence.availabilityEnd).toLocaleString()}</p>
          {occurrenceEditor?.occurrenceId === occurrence.id ? <form onSubmit={event => void submitOccurrenceEditor(event, item, occurrence)} className="mt-4"><h6 className="text-label">{occurrenceEditor.mode === "edit" ? "Edit occurrence start" : "Archive and replace"}</h6>{occurrenceEditor.mode === "replace" && <p className="mt-1 text-body-sm text-ink-secondary">The published occurrence will be archived and a replacement created through the existing server action.</p>}<div className="mt-3"><Field id={`occurrence-edit-${occurrence.id}`} label="New start"><input required type="datetime-local" value={occurrenceEditor.value} onChange={event => setOccurrenceEditor({ ...occurrenceEditor, value: event.target.value })} className="unfar-control" /></Field></div><div className="mt-4 flex flex-col gap-3 sm:flex-row"><Button type="submit" disabled={Boolean(pending)}>{pending === `occurrence:${occurrence.id}:${occurrenceEditor.mode}` ? (occurrenceEditor.mode === "edit" ? "Updating…" : "Replacing…") : "Submit"}</Button><Button variant="secondary" disabled={Boolean(pending)} onClick={() => setOccurrenceEditor(null)}>Cancel</Button></div></form> : <div className="mt-4 flex flex-col gap-3 sm:flex-row sm:flex-wrap">{occurrence.status === "DRAFT" && <Button variant="secondary" disabled={Boolean(pending)} onClick={() => { setEditingId(null); setOccurrenceEditor({ itemId: item.id, occurrenceId: occurrence.id, mode: "edit", value: toLocal(occurrence.availabilityStart) }); }}>Edit start</Button>}{occurrence.status === "DRAFT" && <Button variant="danger" disabled={Boolean(pending)} onClick={() => occurrenceAction(item, occurrence, "", "DELETE")}>{pending === `occurrence:${occurrence.id}:` ? "Deleting…" : "Delete draft"}</Button>}{occurrence.status === "DRAFT" && item.status === "PUBLISHED" && <Button variant="secondary" disabled={Boolean(pending)} onClick={() => occurrenceAction(item, occurrence, "publish")}>{pending === `occurrence:${occurrence.id}:publish` ? "Publishing…" : "Publish occurrence"}</Button>}{occurrence.status === "PUBLISHED" && <Button variant="danger" disabled={Boolean(pending)} onClick={() => occurrenceAction(item, occurrence, "archive")}>{pending === `occurrence:${occurrence.id}:archive` ? "Archiving…" : "Archive occurrence"}</Button>}{occurrence.status === "PUBLISHED" && <Button variant="danger" disabled={Boolean(pending)} onClick={() => { setEditingId(null); setOccurrenceEditor({ itemId: item.id, occurrenceId: occurrence.id, mode: "replace", value: toLocal(occurrence.availabilityStart) }); }}>Archive and replace</Button>}</div>}
        </li>)}</ul>}</section>
      </Surface></li>)}</ul>}
    </section>
    <div className="sr-only" role="status" aria-live="polite">{feedback?.kind === "success" ? feedback.text : ""}</div>
  </section>;
}
