"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import { Button, LiveRegion, MetadataList, Notice, Skeleton, StatePanel, StatusBadge, Surface } from "@/components/ui/primitives";

type Detail={id:string;publicPlaceName:string;coarseLocation:string;privateMeetingDetails:string|null;earliestStart:string;latestStart:string;durationMinutes:number;proposedPriceMinor:number;currency:string;status:string};
const readable=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/^./,letter=>letter.toUpperCase());

export default function JourneyRequestDetail({id,embedded=false,onChanged}:{id:string;embedded?:boolean;onChanged?:()=>void|Promise<void>}){
  const[request,setRequest]=useState<Detail|null>(null),[message,setMessage]=useState(""),[error,setError]=useState(""),[loading,setLoading]=useState(true),[working,setWorking]=useState(false),[confirming,setConfirming]=useState(false);
  const withdrawButton=useRef<HTMLButtonElement>(null);
  const load=useCallback(async()=>{setLoading(true);setError("");try{const response=await fetch(`/api/journey-requests/${id}`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to load Journey Request");setRequest(data.request)}catch(value){setError(value instanceof Error?value.message:"Unable to load Journey Request")}finally{setLoading(false)}},[id]);
  useEffect(()=>{void load()},[load]);
  async function withdraw(){if(working)return;setWorking(true);setError("");try{const response=await fetch(`/api/journey-requests/${id}/withdraw`,{method:"POST"});const data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to withdraw Request");setRequest(data.request);setConfirming(false);setMessage("Journey Request withdrawn and retained in past coordination.");await onChanged?.()}catch(value){setError(value instanceof Error?value.message:"Unable to withdraw Request");await load()}finally{setWorking(false);requestAnimationFrame(()=>withdrawButton.current?.focus())}}
  const content=loading?<Surface aria-busy="true"><Skeleton className="w-1/3"/><Skeleton className="mt-3 w-3/4"/><span className="sr-only" role="status">Loading Request coordination…</span></Surface>:error&&!request?<StatePanel title="Request coordination could not be loaded" tone="danger" action={<Button variant="secondary" onClick={()=>void load()}>Retry this Request</Button>}><p>Other Request records remain available.</p></StatePanel>:request?<><div className="flex flex-wrap items-center justify-between gap-3"><h2 className="text-heading-3">Request details</h2><StatusBadge variant={request.status==="OPEN"?"info":"neutral"}>{readable(request.status)}</StatusBadge></div><MetadataList className="mt-4" items={[{term:"Start window",detail:`${new Date(request.earliestStart).toLocaleString()} – ${new Date(request.latestStart).toLocaleString()}`},{term:"Duration",detail:`${request.durationMinutes} minutes`},{term:"Private meeting details",detail:request.privateMeetingDetails||"None provided"}]}/>{request.status==="OPEN"&&!confirming&&<Button ref={withdrawButton} variant="danger" className="mt-5" onClick={()=>setConfirming(true)}>Withdraw Request</Button>}{request.status==="OPEN"&&confirming&&<Notice className="mt-5" variant="warning" title="Withdraw this Request?"><p>Withdrawal preserves this Request in past coordination and prevents new Proposals.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Button variant="danger" disabled={working} onClick={()=>void withdraw()}>{working?"Withdrawing Request…":"Confirm withdrawal"}</Button><Button variant="secondary" disabled={working} onClick={()=>{setConfirming(false);requestAnimationFrame(()=>withdrawButton.current?.focus())}}>Keep Request</Button></div></Notice>}{error&&<Notice className="mt-4" variant="danger" title="Request action could not be completed"><p>{error}</p></Notice>}<LiveRegion className="mt-4">{message}</LiveRegion></>:null;
  if(embedded)return <section aria-label="Request details">{content}</section>;
  return <main className="mx-auto max-w-2xl px-4 py-10">{request&&<><p className="text-label uppercase text-brand">Journey Request</p><h1 className="mt-2 text-heading-1">{request.publicPlaceName}</h1><p className="mt-2 text-body text-ink-secondary">{request.coarseLocation}</p></>}<div className="mt-6">{content}</div></main>;
}
