"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { ALLOWED_LANGUAGES } from "@/lib/marketplace-vocabulary";
import { createOperatorApplicationController, emptyApplicationForm, safeSupportingUrl, statusCopy, validateApplicationForm, type ApplicationForm, type FieldErrors, type ViewerApplication } from "@/lib/operator-application-ui";

const inputClass = "mt-1 w-full rounded-lg border border-gray-300 px-3 py-2 focus-visible:ring-2 focus-visible:ring-spartan-green";
function date(value: string | null) { return value ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(new Date(value)) : null; }

export default function OperatorApplicationViewer() {
  const controller = useMemo(() => createOperatorApplicationController(fetch), []);
  const [applications, setApplications] = useState<ViewerApplication[]>([]);
  const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState("");
  const [form, setForm] = useState<ApplicationForm>(emptyApplicationForm); const [errors, setErrors] = useState<FieldErrors>({});
  const [message, setMessage] = useState(""); const [submitting, setSubmitting] = useState(false);
  const [confirmId, setConfirmId] = useState<string | null>(null); const [withdrawing, setWithdrawing] = useState(false);
  const dialogRef = useRef<HTMLElement>(null); const cancelRef = useRef<HTMLButtonElement>(null); const returnFocus = useRef<HTMLButtonElement | null>(null);
  const load = useCallback(async () => { setLoadError(""); try { const response = await fetch("/api/operator-applications", { cache: "no-store" }); if (!response.ok || !response.headers.get("content-type")?.includes("application/json")) throw new Error(); const body: unknown = await response.json(); if (!body || typeof body !== "object" || !("applications" in body) || !Array.isArray(body.applications)) throw new Error(); setApplications(body.applications as ViewerApplication[]); } catch { setLoadError("Your application history could not be loaded. Please try again."); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (confirmId) cancelRef.current?.focus(); }, [confirmId]);
  const pending = applications.find(item => item.status === "PENDING"); const latest = applications[0];
  const update = (key: keyof ApplicationForm, value: string | string[]) => { setForm(current => ({ ...current, [key]: value })); setErrors(current => ({ ...current, [key]: undefined })); };
  async function submit(event: React.FormEvent) { event.preventDefault(); if (submitting) return; const nextErrors = validateApplicationForm(form); setErrors(nextErrors); if (Object.keys(nextErrors).length) { setMessage("Check the highlighted fields before submitting."); return; } setSubmitting(true); setMessage(""); const outcome = await controller.submit(form, load); setSubmitting(false); setMessage(outcome.message); if (outcome.kind === "success") { setForm(emptyApplicationForm()); setErrors({}); } }
  async function withdraw() { if (!confirmId || withdrawing) return; setWithdrawing(true); setMessage(""); const outcome = await controller.withdraw(confirmId, load); setWithdrawing(false); setMessage(outcome.message); if (outcome.kind === "success") { setConfirmId(null); returnFocus.current?.focus(); } }
  return <main className="mx-auto max-w-4xl px-4 py-10">
    <p className="text-sm font-semibold uppercase tracking-wide text-spartan-green">Viewer account</p><h1 className="mt-1 text-3xl font-bold">Operator application</h1><p className="mt-2 text-gray-600">Share your qualifications and availability for administrator review. Submission does not guarantee approval or a review timeline.</p>
    {(message || loadError) && <div className="mt-5 rounded-lg border border-gray-300 bg-white p-3" role="alert" aria-live="assertive">{message || loadError}</div>}
    {loading ? <p className="mt-8" role="status">Loading application history…</p> : <>
      <section className="mt-8" aria-labelledby="current-application"><h2 id="current-application" className="text-xl font-semibold">Current status</h2>{latest ? <ApplicationCard application={latest} prominent onWithdraw={latest.status === "PENDING" ? event => { returnFocus.current = event.currentTarget; setConfirmId(latest.id); } : undefined} /> : <p className="mt-3 rounded-xl border bg-white p-5">You have not submitted an Operator application yet.</p>}</section>
      {!pending && <ApplicationFormView form={form} errors={errors} submitting={submitting} onUpdate={update} onSubmit={submit} />}
      {pending && <p className="mt-8 rounded-xl border border-amber-200 bg-amber-50 p-4">You already have a pending application. You can submit another after it reaches a terminal status or is withdrawn.</p>}
      {applications.length > 1 && <section className="mt-10" aria-labelledby="history-heading"><h2 id="history-heading" className="text-xl font-semibold">Application history</h2><div className="mt-3 space-y-4">{applications.slice(1).map(item => <ApplicationCard key={item.id} application={item} />)}</div></section>}
    </>}
    {confirmId && <div className="fixed inset-0 z-50 grid place-items-center bg-black/50 p-4" role="presentation" onMouseDown={event => { if (event.target === event.currentTarget && !withdrawing) { setConfirmId(null); returnFocus.current?.focus(); } }}><section ref={dialogRef} role="dialog" aria-modal="true" aria-labelledby="withdraw-title" className="w-full max-w-md rounded-xl bg-white p-6 shadow-xl" onKeyDown={event => { if (event.key === "Escape" && !withdrawing) { setConfirmId(null); returnFocus.current?.focus(); } if (event.key === "Tab") { const controls = [...(dialogRef.current?.querySelectorAll<HTMLElement>("button:not(:disabled)") ?? [])]; if (!controls.length) return; const index = controls.indexOf(document.activeElement as HTMLElement); const next = event.shiftKey ? (index <= 0 ? controls.length - 1 : index - 1) : (index >= controls.length - 1 ? 0 : index + 1); event.preventDefault(); controls[next].focus(); } }}><h2 id="withdraw-title" className="text-xl font-semibold">Withdraw this application?</h2><p className="mt-2 text-gray-600">The application will remain in your history and cannot be restored to pending.</p><div className="mt-6 flex flex-col-reverse gap-3 sm:flex-row sm:justify-end"><button ref={cancelRef} type="button" disabled={withdrawing} onClick={() => { setConfirmId(null); returnFocus.current?.focus(); }} className="min-h-11 rounded-lg border px-4 disabled:opacity-50">Keep application</button><button type="button" disabled={withdrawing} onClick={withdraw} className="min-h-11 rounded-lg bg-red-700 px-4 font-semibold text-white disabled:opacity-50">{withdrawing ? "Withdrawing…" : "Confirm withdrawal"}</button></div></section></div>}
  </main>;
}

function ApplicationFormView({ form, errors, submitting, onUpdate, onSubmit }: { form: ApplicationForm; errors: FieldErrors; submitting: boolean; onUpdate: (key: keyof ApplicationForm, value: string | string[]) => void; onSubmit: (event: React.FormEvent) => void }) {
  const text = (key: "qualifications" | "relevantExperience" | "availability" | "additionalNote", label: string, min: number, max: number, optional = false) => <div><label htmlFor={key} className="font-medium">{label}{optional ? " (optional)" : ""}</label><textarea id={key} value={form[key]} minLength={optional ? undefined : min} maxLength={max} aria-invalid={Boolean(errors[key])} aria-describedby={`${key}-help ${key}-error`} onChange={event => onUpdate(key, event.target.value)} className={inputClass} rows={key === "additionalNote" ? 4 : 5}/><div id={`${key}-help`} className="flex justify-between text-xs text-gray-500"><span>{optional ? `Up to ${max.toLocaleString()} characters` : `${min}–${max.toLocaleString()} characters`}</span><span>{form[key].length}/{max}</span></div>{errors[key] && <p id={`${key}-error`} className="text-sm text-red-700">{errors[key]}</p>}</div>;
  return <section className="mt-10 rounded-xl border bg-white p-5 sm:p-7" aria-labelledby="apply-heading"><h2 id="apply-heading" className="text-xl font-semibold">Apply to become an Operator</h2><form className="mt-6 space-y-5" noValidate onSubmit={onSubmit}>{text("qualifications", "Qualifications", 20, 2000)}{text("relevantExperience", "Relevant experience", 20, 2000)}<fieldset aria-describedby="languages-help languages-error"><legend className="font-medium">Languages</legend><p id="languages-help" className="text-sm text-gray-500">Choose 1 to 4 languages.</p><div className="mt-2 grid gap-2 sm:grid-cols-2">{ALLOWED_LANGUAGES.map(language => <label key={language} className="flex min-h-11 items-center gap-3 rounded-lg border px-3"><input type="checkbox" checked={form.languages.includes(language)} disabled={!form.languages.includes(language) && form.languages.length >= 4} onChange={event => onUpdate("languages", event.target.checked ? [...new Set([...form.languages, language])] : form.languages.filter(item => item !== language))}/>{language}</label>)}</div>{errors.languages && <p id="languages-error" className="text-sm text-red-700">{errors.languages}</p>}</fieldset>{text("availability", "Availability", 10, 1000)}<div><label htmlFor="supportingUrl" className="font-medium">Supporting URL (optional)</label><input id="supportingUrl" type="url" inputMode="url" value={form.supportingUrl} maxLength={500} placeholder="https://example.com/qualifications" aria-invalid={Boolean(errors.supportingUrl)} aria-describedby="supportingUrl-help supportingUrl-error" onChange={event => onUpdate("supportingUrl", event.target.value)} className={inputClass}/><p id="supportingUrl-help" className="text-xs text-gray-500">HTTPS only, up to 500 characters.</p>{errors.supportingUrl && <p id="supportingUrl-error" className="text-sm text-red-700">{errors.supportingUrl}</p>}</div>{text("additionalNote", "Additional note", 0, 1000, true)}<button type="submit" disabled={submitting} className="min-h-12 w-full rounded-lg bg-spartan-green px-5 font-semibold text-white disabled:opacity-50">{submitting ? "Submitting…" : "Submit application"}</button></form></section>;
}

function ApplicationCard({ application, prominent = false, onWithdraw }: { application: ViewerApplication; prominent?: boolean; onWithdraw?: (event: React.MouseEvent<HTMLButtonElement>) => void }) { const supportingUrl = safeSupportingUrl(application.supportingUrl); return <article className={`mt-3 rounded-xl border bg-white p-5 ${prominent ? "border-spartan-green shadow-sm" : "border-gray-200"}`}><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-lg font-semibold">{statusCopy[application.status].label} application</h3><span className="rounded-full border px-3 py-1 text-sm font-semibold">Status: {statusCopy[application.status].label}</span></div><p className="mt-3 text-sm text-gray-700">{statusCopy[application.status].next}</p><dl className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><div><dt className="font-medium">Submitted</dt><dd>{date(application.submittedAt)}</dd></div>{application.reviewedAt && <div><dt className="font-medium">Reviewed</dt><dd>{date(application.reviewedAt)}</dd></div>}{application.withdrawnAt && <div><dt className="font-medium">Withdrawn</dt><dd>{date(application.withdrawnAt)}</dd></div>}<div><dt className="font-medium">Languages</dt><dd>{application.languages.join(", ")}</dd></div></dl>{application.reviewNote && <div className="mt-4 rounded-lg bg-gray-50 p-4"><h4 className="font-semibold">Administrator feedback</h4><p className="mt-1 whitespace-pre-wrap text-sm">{application.reviewNote}</p></div>}{supportingUrl && <p className="mt-4"><a href={supportingUrl} target="_blank" rel="noopener noreferrer" className="font-medium text-spartan-green underline">Open supporting information <span className="sr-only">(opens in a new tab)</span></a></p>}{onWithdraw && <button type="button" onClick={onWithdraw} className="mt-5 min-h-11 rounded-lg border border-red-700 px-4 font-semibold text-red-700">Withdraw application</button>}</article>; }
