"use client";

import { useCallback, useEffect, useRef, useState } from "react";
import AgreementConfirmation from "@/components/AgreementConfirmation";
import { Button, Field, LiveRegion, MetadataList, Notice, Skeleton, StatePanel, StatusBadge, Surface } from "@/components/ui/primitives";

type Proposal={id:string;teleporterName:string;version:number;status:string;earliestStart:string;latestStart:string|null;durationMinutes:number;proposedPriceMinor:number;currency:string};
const localInput=(instant:string)=>{const date=new Date(instant);const offset=date.getTimezoneOffset()*60_000;return new Date(date.getTime()-offset).toISOString().slice(0,16)};
const readable=(value:string)=>value.replaceAll("_"," ").toLowerCase().replace(/^./,letter=>letter.toUpperCase());

export default function ReceivedProposals({requestId,embedded=false}:{requestId:string;embedded?:boolean}){
  const[proposals,setProposals]=useState<Proposal[]>([]),[starts,setStarts]=useState<Record<string,string>>({}),[message,setMessage]=useState(""),[error,setError]=useState(""),[busyId,setBusyId]=useState<string|null>(null),[confirmed,setConfirmed]=useState(0),[loading,setLoading]=useState(true),[decliningId,setDecliningId]=useState<string|null>(null);
  const actionRef=useRef<HTMLButtonElement>(null);
  const load=useCallback(async(background=false)=>{if(!background)setLoading(true);setError("");try{const response=await fetch(`/api/journey-requests/${requestId}/proposals`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to load Proposals");setProposals(data.proposals??[])}catch(value){setError(value instanceof Error?value.message:"Unable to load Proposals")}finally{setLoading(false)}},[requestId]);
  useEffect(()=>{void load()},[load]);
  async function decline(id:string){if(busyId)return;setBusyId(id);setError("");try{const response=await fetch(`/api/journey-requests/${requestId}/proposals/${id}/decline`,{method:"POST"});const data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to decline Proposal");setMessage("Proposal declined and preserved in coordination history.");setDecliningId(null);await load(true)}catch(value){setError(value instanceof Error?value.message:"Unable to decline Proposal");await load(true)}finally{setBusyId(null);requestAnimationFrame(()=>actionRef.current?.focus())}}
  async function accept(proposal:Proposal){if(busyId)return;const selected=starts[proposal.id];if(proposal.latestStart&&!selected){setError("Choose a start within the available window.");return}setBusyId(proposal.id);setError("");let body:string|undefined;try{if(proposal.latestStart)body=JSON.stringify({scheduledStartAt:new Date(selected).toISOString()});const response=await fetch(`/api/journey-requests/${requestId}/proposals/${proposal.id}/accept`,{method:"POST",headers:body?{"Content-Type":"application/json"}:undefined,body});const data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to confirm Journey");setMessage(data.created?"Proposal accepted. Agreement and Journey confirmed.":"Existing confirmation restored.");setConfirmed(value=>value+1);await load(true)}catch(value){setError(value instanceof Error?value.message:"Unable to accept Proposal");await load(true)}finally{setBusyId(null)}}
  const proposalContent=loading?<Surface aria-busy="true"><Skeleton className="w-1/3"/><Skeleton className="mt-3 w-2/3"/><span className="sr-only" role="status">Loading Proposals…</span></Surface>:error&&proposals.length===0?<StatePanel title="Proposals could not be loaded" tone="danger" action={<Button variant="secondary" onClick={()=>void load()}>Retry Proposals for this Request</Button>}><p>The Request details remain available.</p></StatePanel>:proposals.length===0?<StatePanel title="Awaiting a Proposal"><p>No Proposals have been received for this Request.</p></StatePanel>:<div className="grid gap-4">{proposals.map(proposal=>{const active=proposal.status==="ACTIVE";return <Surface key={proposal.id} className="break-words"><div className="flex flex-wrap items-center justify-between gap-2"><h3 className="text-heading-3">Proposal version {proposal.version}</h3><StatusBadge variant={active?"info":proposal.status==="ACCEPTED"?"success":"neutral"}>{readable(proposal.status)}</StatusBadge></div><MetadataList className="mt-4" items={[{term:"Teleporter",detail:proposal.teleporterName},{term:"Duration",detail:`${proposal.durationMinutes} minutes`},{term:proposal.latestStart?"Available start window":"Fixed start",detail:proposal.latestStart?`${new Date(proposal.earliestStart).toLocaleString()} – ${new Date(proposal.latestStart).toLocaleString()}`:new Date(proposal.earliestStart).toLocaleString()}]}/>{active&&proposal.latestStart&&<div className="mt-4"><Field id={`proposal-start-${proposal.id}`} label="Choose confirmed start"><input required type="datetime-local" min={localInput(proposal.earliestStart)} max={localInput(proposal.latestStart)} value={starts[proposal.id]??""} onChange={event=>setStarts(value=>({...value,[proposal.id]:event.target.value}))} className="unfar-control"/></Field></div>}{active&&decliningId!==proposal.id&&<div className="mt-5 flex flex-col gap-2 sm:flex-row"><Button ref={actionRef} disabled={busyId!==null||Boolean(proposal.latestStart&&!starts[proposal.id])} onClick={()=>void accept(proposal)}>{busyId===proposal.id?"Accepting Proposal…":"Accept Proposal"}</Button><Button variant="danger" disabled={busyId!==null} onClick={()=>setDecliningId(proposal.id)}>Decline Proposal</Button></div>}{active&&decliningId===proposal.id&&<Notice className="mt-5" variant="warning" title="Decline this Proposal?"><p>The Proposal will remain in coordination history and cannot be accepted afterward.</p><div className="mt-3 flex flex-col gap-2 sm:flex-row"><Button variant="danger" disabled={busyId!==null} onClick={()=>void decline(proposal.id)}>{busyId===proposal.id?"Declining Proposal…":"Confirm decline"}</Button><Button variant="secondary" disabled={busyId!==null} onClick={()=>{setDecliningId(null);requestAnimationFrame(()=>actionRef.current?.focus())}}>Keep Proposal</Button></div></Notice>}</Surface>})}</div>;
  const content=<><AgreementConfirmation requestId={requestId} refresh={confirmed} embedded/><section className="mt-6" aria-labelledby={`proposals-${requestId}`}><h2 id={`proposals-${requestId}`} className="text-heading-3">Proposals</h2><p className="mt-2 text-body-sm text-ink-secondary">Accepting an eligible Proposal creates one confirmed Agreement and Journey.</p><div className="mt-4">{proposalContent}</div>{error&&proposals.length>0&&<Notice className="mt-4" variant="danger" title="Proposal action could not be completed"><p>{error}</p></Notice>}<LiveRegion className="mt-4">{message}</LiveRegion></section></>;
  return embedded?<div>{content}</div>:<section className="mx-auto mt-8 max-w-2xl px-4 pb-10">{content}</section>;
}
