"use client";

import { useCallback, useEffect, useState } from "react";
import AgreementConfirmation from "@/components/AgreementConfirmation";

type Proposal = { id:string; teleporterName:string; version:number; status:string; earliestStart:string; latestStart:string|null; durationMinutes:number; proposedPriceMinor:number; currency:string };
const localInput = (instant: string) => { const date = new Date(instant); const offset = date.getTimezoneOffset() * 60_000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); };

export default function ReceivedProposals({ requestId }: { requestId: string }) {
  const [proposals,setProposals]=useState<Proposal[]>([]),[starts,setStarts]=useState<Record<string,string>>({}),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[confirmed,setConfirmed]=useState(0);
  const load=useCallback(async()=>{const response=await fetch(`/api/journey-requests/${requestId}/proposals`,{cache:"no-store"});const data=await response.json();if(!response.ok)throw new Error(data.error??"Unable to load Proposals");setProposals(data.proposals??[])},[requestId]);
  useEffect(()=>{void load().catch(error=>setMessage(error.message))},[load]);
  async function decline(id:string){const response=await fetch(`/api/journey-requests/${requestId}/proposals/${id}/decline`,{method:"POST"});const data=await response.json();if(!response.ok)return setMessage(data.error??"Unable to decline Proposal");setMessage("Proposal declined and preserved in history.");await load()}
  async function accept(proposal:Proposal){if(busy)return;const selected=starts[proposal.id];if(proposal.latestStart&&!selected)return setMessage("Choose a start within the available window.");setBusy(true);setMessage("");let body:string|undefined;try{if(proposal.latestStart)body=JSON.stringify({scheduledStartAt:new Date(selected).toISOString()})}catch{setBusy(false);return setMessage("Choose a valid scheduled start.")}const response=await fetch(`/api/journey-requests/${requestId}/proposals/${proposal.id}/accept`,{method:"POST",headers:body?{"Content-Type":"application/json"}:undefined,body});const data=await response.json();setBusy(false);if(!response.ok)return setMessage(data.error??"Unable to confirm Journey");setMessage(data.created?"Journey confirmed.":"Existing confirmation restored.");setConfirmed(value=>value+1);await load()}
  return <><AgreementConfirmation requestId={requestId} refresh={confirmed}/><section className="mx-auto mt-8 max-w-2xl px-4 pb-10"><h2 className="text-xl font-semibold">Received Proposals</h2><p className="mt-1 text-sm text-gray-600">Accepting creates one confirmed Agreement and Journey.</p>{message&&<p role="status" className="mt-3">{message}</p>}{proposals.length===0?<p className="mt-3 text-gray-500">No Proposals received.</p>:<ul className="mt-3 divide-y rounded-xl border bg-white">{proposals.map(proposal=><li key={proposal.id} className="p-4"><p className="font-semibold">{proposal.teleporterName} · Version {proposal.version}</p><p className="text-sm">{proposal.status.replaceAll("_"," ")} · {proposal.durationMinutes} min · {proposal.proposedPriceMinor} {proposal.currency}</p>{proposal.latestStart?<><p className="mt-1 text-sm">Available start window: {new Date(proposal.earliestStart).toLocaleString()} – {new Date(proposal.latestStart).toLocaleString()}</p>{proposal.status==="ACTIVE"&&<label className="mt-3 block text-sm font-medium">Choose confirmed start<input required type="datetime-local" min={localInput(proposal.earliestStart)} max={localInput(proposal.latestStart)} value={starts[proposal.id]??""} onChange={event=>setStarts(value=>({...value,[proposal.id]:event.target.value}))} className="mt-1 min-h-11 w-full rounded-lg border px-3"/></label>}</>:<p className="text-sm">Fixed start: {new Date(proposal.earliestStart).toLocaleString()}</p>}{proposal.status==="ACTIVE"&&<div className="mt-3 flex gap-2"><button disabled={busy||Boolean(proposal.latestStart&&!starts[proposal.id])} onClick={()=>void accept(proposal)} className="min-h-11 rounded-lg bg-spartan-green px-4 font-semibold text-white disabled:opacity-50">Accept Proposal</button><button disabled={busy} onClick={()=>void decline(proposal.id)} className="min-h-11 rounded-lg border border-red-700 px-4 text-red-800 disabled:opacity-50">Decline</button></div>}</li>)}</ul>}</section></>;
}
