import "server-only";

import { JourneyReviewRole, Prisma, PrismaClient, TripStatus } from "@prisma/client";
import { publicDisplayName } from "./profiles";

type Database = PrismaClient;
type Code = "INVALID_REVIEW"|"INVALID_REPUTATION_CURSOR"|"JOURNEY_NOT_FOUND"|"JOURNEY_NOT_COMPLETED"|"REVIEW_WINDOW_CLOSED"|"REVIEW_ALREADY_SUBMITTED"|"JOURNEY_REVIEW_UNSUPPORTED"|"REVIEW_CHANGED_CONCURRENTLY";
const failed=(status:400|404|409|503,code:Code,error:string)=>({ok:false as const,status,code,error});
const clock=async(tx:Prisma.TransactionClient)=>(await tx.$queryRaw<Array<{now:Date}>>(Prisma.sql`SELECT CURRENT_TIMESTAMP AS now`))[0].now;
const participant=(trip:{viewerId:string;operatorId:string|null},actorId:string)=>trip.viewerId===actorId?{reviewerId:trip.viewerId,revieweeId:trip.operatorId!,reviewerRole:JourneyReviewRole.EXPLORER,revieweeRole:JourneyReviewRole.TELEPORTER}:trip.operatorId===actorId?{reviewerId:trip.operatorId,revieweeId:trip.viewerId,reviewerRole:JourneyReviewRole.TELEPORTER,revieweeRole:JourneyReviewRole.EXPLORER}:null;
const validReview=(review:{reviewerId:string;revieweeId:string;reviewerRole:JourneyReviewRole;revieweeRole:JourneyReviewRole},trip:{viewerId:string;operatorId:string|null})=>review.reviewerRole===JourneyReviewRole.EXPLORER?review.reviewerId===trip.viewerId&&review.revieweeId===trip.operatorId&&review.revieweeRole===JourneyReviewRole.TELEPORTER:review.reviewerRole===JourneyReviewRole.TELEPORTER&&review.reviewerId===trip.operatorId&&review.revieweeId===trip.viewerId&&review.revieweeRole===JourneyReviewRole.EXPLORER;
const safeReview=(review:{rating:number;comment:string|null;submittedAt:Date;reviewerRole:JourneyReviewRole;reviewer:{name:string|null}})=>({rating:review.rating,comment:review.comment,submittedAt:review.submittedAt,author:{role:review.reviewerRole,displayName:publicDisplayName(review.reviewer.name)}});
const normalize=(input:{rating?:unknown;comment?:unknown})=>{if(!Number.isInteger(input.rating)||Number(input.rating)<1||Number(input.rating)>5)return null;if(input.comment!==undefined&&input.comment!==null&&typeof input.comment!=="string")return null;const comment=typeof input.comment==="string"?input.comment.trim():"";if(comment.length>1000||/[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/.test(comment))return null;return{rating:Number(input.rating),comment:comment||null}};
const completed=(status:TripStatus)=>status===TripStatus.ENDED||status===TripStatus.FEEDBACK_COMPLETED;

export const REVIEW_REPUTATION_DEFAULT_LIMIT=20;
export const REVIEW_REPUTATION_MAX_LIMIT=50;
type Cursor={v:1;u:string;r:JourneyReviewRole;s:string;i:string};
const encodeCursor=(value:Cursor)=>Buffer.from(JSON.stringify(value),"utf8").toString("base64url");
function decodeCursor(value:string|undefined,userId:string,role:JourneyReviewRole){if(!value)return null;try{if(!/^[A-Za-z0-9_-]+$/.test(value))throw new Error();const bytes=Buffer.from(value,"base64url");if(bytes.toString("base64url")!==value)throw new Error();const parsed=JSON.parse(bytes.toString("utf8")) as Record<string,unknown>;if(Object.keys(parsed).sort().join(",")!=="i,r,s,u,v"||parsed.v!==1||parsed.u!==userId||parsed.r!==role||typeof parsed.s!=="string"||typeof parsed.i!=="string"||!/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(parsed.i))throw new Error();const submittedAt=new Date(parsed.s);if(Number.isNaN(submittedAt.getTime())||submittedAt.toISOString()!==parsed.s)throw new Error();return{submittedAt,id:parsed.i}}catch{throw new Error("INVALID_REPUTATION_CURSOR")}}

export async function getJourneyReviewState(db:Database,actorId:string,tripId:string){return db.$transaction(async tx=>{const now=await clock(tx);const trip=await tx.trip.findUnique({where:{id:tripId},select:{viewerId:true,operatorId:true,status:true,endedAt:true,reviewDeadlineAt:true,reviews:{include:{reviewer:{select:{name:true}}},orderBy:[{submittedAt:"asc"},{id:"asc"}]}}});const performed=trip&&participant(trip,actorId);if(!trip||!performed)return failed(404,"JOURNEY_NOT_FOUND","Journey not found");const supported=Boolean(trip.operatorId&&trip.viewerId!==trip.operatorId&&trip.endedAt&&trip.reviewDeadlineAt&&completed(trip.status));const valid=trip.reviews.filter(value=>validReview(value,trip));const both=valid.length===2&&new Set(valid.map(value=>value.reviewerRole)).size===2;const revealed=supported&&Boolean(both||now>=trip.reviewDeadlineAt!);const own=valid.find(value=>value.reviewerId===actorId);return{ok:true as const,value:{eligible:supported&&now<trip.reviewDeadlineAt!,deadlineAt:trip.reviewDeadlineAt,performedRole:performed.reviewerRole,canSubmit:supported&&now<trip.reviewDeadlineAt!&&!own,myReview:own?{rating:own.rating,comment:own.comment,submittedAt:own.submittedAt}:null,revealedReviews:revealed?valid.map(safeReview):[]}}},{isolationLevel:Prisma.TransactionIsolationLevel.RepeatableRead})}

export async function getJourneyReviewContext(db:Database,actorId:string,tripId:string,cursor?:string,limit=REVIEW_REPUTATION_DEFAULT_LIMIT){const state=await getJourneyReviewState(db,actorId,tripId);if(!state.ok)return state;const trip=await db.trip.findUnique({where:{id:tripId},select:{viewerId:true,operatorId:true}}),performed=trip&&participant(trip,actorId);if(!trip||!performed)return failed(404,"JOURNEY_NOT_FOUND","Journey not found");try{const reputation=await getRoleReputation(db,performed.revieweeId,performed.revieweeRole,cursor,limit);return{ok:true as const,value:{...state.value,counterpartyRole:performed.revieweeRole,reputation}}}catch(error){if(error instanceof Error&&error.message==="INVALID_REPUTATION_CURSOR")return failed(400,"INVALID_REPUTATION_CURSOR","Invalid reputation cursor");throw error}}

export async function submitJourneyReview(db:Database,actorId:string,tripId:string,input:{rating?:unknown;comment?:unknown}){const value=normalize(input);if(!value)return failed(400,"INVALID_REVIEW","Choose a rating from 1 to 5 and an optional comment of at most 1,000 characters");try{return await db.$transaction(async tx=>{await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "Trip" WHERE "id"=${tripId} FOR UPDATE`);const now=await clock(tx);const trip=await tx.trip.findUnique({where:{id:tripId},select:{viewerId:true,operatorId:true,status:true,endedAt:true,reviewDeadlineAt:true}});const performed=trip&&participant(trip,actorId);if(!trip||!performed)return failed(404,"JOURNEY_NOT_FOUND","Journey not found");if(!completed(trip.status))return failed(409,"JOURNEY_NOT_COMPLETED","Journey has not been completed");if(!trip.operatorId||trip.viewerId===trip.operatorId||!trip.endedAt||!trip.reviewDeadlineAt)return failed(409,"JOURNEY_REVIEW_UNSUPPORTED","Journey does not support participant reviews");const existing=await tx.journeyReview.findUnique({where:{tripId_reviewerId:{tripId,reviewerId:actorId}}});if(existing)return existing.rating===value.rating&&existing.comment===value.comment?{ok:true as const,value:{rating:existing.rating,comment:existing.comment,submittedAt:existing.submittedAt},created:false}:failed(409,"REVIEW_ALREADY_SUBMITTED","A review has already been submitted for this Journey");if(now>=trip.reviewDeadlineAt)return failed(409,"REVIEW_WINDOW_CLOSED","The review window has closed");const created=await tx.journeyReview.create({data:{tripId,...performed,rating:value.rating,comment:value.comment}});return{ok:true as const,value:{rating:created.rating,comment:created.comment,submittedAt:created.submittedAt},created:true}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2034")return failed(503,"REVIEW_CHANGED_CONCURRENTLY","Review state changed concurrently; try again");if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002"&&JSON.stringify(error.meta??{}).includes("JourneyReview"))return failed(409,"REVIEW_ALREADY_SUBMITTED","A review has already been submitted for this Journey");if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2004"){const details=JSON.stringify(error.meta??{});if(details.includes("JourneyReview_submission_window_check"))return failed(409,"REVIEW_WINDOW_CLOSED","The review window has closed");return failed(409,"JOURNEY_REVIEW_UNSUPPORTED","Journey does not support this review")};throw error}}

export async function getRoleReputation(db:Database,userId:string,performedRole:JourneyReviewRole,cursor?:string,limit=REVIEW_REPUTATION_DEFAULT_LIMIT){if(!Number.isInteger(limit)||limit<1||limit>REVIEW_REPUTATION_MAX_LIMIT)throw new Error("INVALID_REPUTATION_CURSOR");const decoded=decodeCursor(cursor,userId,performedRole),cursorClause=decoded?Prisma.sql`AND (r."submittedAt", r."id") < (${decoded.submittedAt}, ${decoded.id}::uuid)`:Prisma.empty,reveal=Prisma.sql`(t."reviewDeadlineAt" <= CURRENT_TIMESTAMP OR EXISTS (SELECT 1 FROM "JourneyReview" other WHERE other."tripId"=r."tripId" AND other."reviewerRole"<>r."reviewerRole"))`;const aggregate=(await db.$queryRaw<Array<{average:number|null;count:bigint}>>(Prisma.sql`SELECT avg(r.rating)::float8 AS average, count(*)::bigint AS count FROM "JourneyReview" r JOIN "Trip" t ON t.id=r."tripId" WHERE r."revieweeId"=${userId} AND r."revieweeRole"=${performedRole}::"JourneyReviewRole" AND ${reveal}`))[0];const rows=await db.$queryRaw<Array<{id:string;rating:number;comment:string|null;submittedAt:Date;reviewerRole:JourneyReviewRole;name:string|null}>>(Prisma.sql`SELECT r.id,r.rating,r.comment,r."submittedAt",r."reviewerRole",u.name FROM "JourneyReview" r JOIN "Trip" t ON t.id=r."tripId" JOIN "User" u ON u.id=r."reviewerId" WHERE r."revieweeId"=${userId} AND r."revieweeRole"=${performedRole}::"JourneyReviewRole" AND ${reveal} ${cursorClause} ORDER BY r."submittedAt" DESC,r.id DESC LIMIT ${limit+1}`);const page=rows.slice(0,limit),last=page.at(-1);return{average:aggregate.average,count:Number(aggregate.count),comments:page.map(row=>safeReview({...row,reviewer:{name:row.name}})),nextCursor:rows.length>limit&&last?encodeCursor({v:1,u:userId,r:performedRole,s:last.submittedAt.toISOString(),i:last.id}):null}}
