import "server-only";

import { JourneyReviewRole, Prisma, PrismaClient, TripStatus } from "@prisma/client";
import { publicDisplayName } from "./profiles";

type Database = PrismaClient;
type Code = "INVALID_REVIEW"|"JOURNEY_NOT_FOUND"|"JOURNEY_NOT_COMPLETED"|"REVIEW_WINDOW_CLOSED"|"REVIEW_ALREADY_SUBMITTED"|"JOURNEY_REVIEW_UNSUPPORTED"|"REVIEW_CHANGED_CONCURRENTLY";
const failed=(status:400|404|409|503,code:Code,error:string)=>({ok:false as const,status,code,error});
const clock=async(tx:Prisma.TransactionClient)=>(await tx.$queryRaw<Array<{now:Date}>>(Prisma.sql`SELECT CURRENT_TIMESTAMP AS now`))[0].now;
const participant=(trip:{viewerId:string;operatorId:string|null},actorId:string)=>trip.viewerId===actorId?{reviewerId:trip.viewerId,revieweeId:trip.operatorId!,reviewerRole:JourneyReviewRole.EXPLORER,revieweeRole:JourneyReviewRole.TELEPORTER}:trip.operatorId===actorId?{reviewerId:trip.operatorId,revieweeId:trip.viewerId,reviewerRole:JourneyReviewRole.TELEPORTER,revieweeRole:JourneyReviewRole.EXPLORER}:null;
const validReview=(review:{reviewerId:string;revieweeId:string;reviewerRole:JourneyReviewRole;revieweeRole:JourneyReviewRole},trip:{viewerId:string;operatorId:string|null})=>review.reviewerRole===JourneyReviewRole.EXPLORER?review.reviewerId===trip.viewerId&&review.revieweeId===trip.operatorId&&review.revieweeRole===JourneyReviewRole.TELEPORTER:review.reviewerRole===JourneyReviewRole.TELEPORTER&&review.reviewerId===trip.operatorId&&review.revieweeId===trip.viewerId&&review.revieweeRole===JourneyReviewRole.EXPLORER;
const safeReview=(review:{rating:number;comment:string|null;submittedAt:Date;reviewerRole:JourneyReviewRole;reviewer:{name:string|null}})=>({rating:review.rating,comment:review.comment,submittedAt:review.submittedAt,author:{role:review.reviewerRole,displayName:publicDisplayName(review.reviewer.name)}});
const normalize=(input:{rating?:unknown;comment?:unknown})=>{if(!Number.isInteger(input.rating)||Number(input.rating)<1||Number(input.rating)>5)return null;if(input.comment!==undefined&&input.comment!==null&&typeof input.comment!=="string")return null;const comment=typeof input.comment==="string"?input.comment.trim():"";if(comment.length>1000)return null;return{rating:Number(input.rating),comment:comment||null}};
const completed=(status:TripStatus)=>status===TripStatus.ENDED||status===TripStatus.FEEDBACK_COMPLETED;

export async function getJourneyReviewState(db:Database,actorId:string,tripId:string){return db.$transaction(async tx=>{const now=await clock(tx);const trip=await tx.trip.findUnique({where:{id:tripId},select:{viewerId:true,operatorId:true,status:true,endedAt:true,reviewDeadlineAt:true,reviews:{include:{reviewer:{select:{name:true}}},orderBy:[{submittedAt:"asc"},{id:"asc"}]}}});const performed=trip&&participant(trip,actorId);if(!trip||!performed)return failed(404,"JOURNEY_NOT_FOUND","Journey not found");const supported=Boolean(trip.operatorId&&trip.viewerId!==trip.operatorId&&trip.endedAt&&trip.reviewDeadlineAt&&completed(trip.status));const valid=trip.reviews.filter(value=>validReview(value,trip));const both=valid.length===2&&new Set(valid.map(value=>value.reviewerRole)).size===2;const revealed=supported&&Boolean(both||now>=trip.reviewDeadlineAt!);const own=valid.find(value=>value.reviewerId===actorId);return{ok:true as const,value:{eligible:supported&&now<trip.reviewDeadlineAt!,deadlineAt:trip.reviewDeadlineAt,performedRole:performed.reviewerRole,canSubmit:supported&&now<trip.reviewDeadlineAt!&&!own,myReview:own?{rating:own.rating,comment:own.comment,submittedAt:own.submittedAt}:null,revealedReviews:revealed?valid.map(safeReview):[]}}},{isolationLevel:Prisma.TransactionIsolationLevel.RepeatableRead})}

export async function submitJourneyReview(db:Database,actorId:string,tripId:string,input:{rating?:unknown;comment?:unknown}){const value=normalize(input);if(!value)return failed(400,"INVALID_REVIEW","Choose a rating from 1 to 5 and an optional comment of at most 1,000 characters");try{return await db.$transaction(async tx=>{await tx.$queryRaw(Prisma.sql`SELECT "id" FROM "Trip" WHERE "id"=${tripId} FOR UPDATE`);const now=await clock(tx);const trip=await tx.trip.findUnique({where:{id:tripId},select:{viewerId:true,operatorId:true,status:true,endedAt:true,reviewDeadlineAt:true}});const performed=trip&&participant(trip,actorId);if(!trip||!performed)return failed(404,"JOURNEY_NOT_FOUND","Journey not found");if(!completed(trip.status))return failed(409,"JOURNEY_NOT_COMPLETED","Journey has not been completed");if(!trip.operatorId||trip.viewerId===trip.operatorId||!trip.endedAt||!trip.reviewDeadlineAt)return failed(409,"JOURNEY_REVIEW_UNSUPPORTED","Journey does not support participant reviews");const existing=await tx.journeyReview.findUnique({where:{tripId_reviewerId:{tripId,reviewerId:actorId}}});if(existing)return existing.rating===value.rating&&existing.comment===value.comment?{ok:true as const,value:{rating:existing.rating,comment:existing.comment,submittedAt:existing.submittedAt},created:false}:failed(409,"REVIEW_ALREADY_SUBMITTED","A review has already been submitted for this Journey");if(now>=trip.reviewDeadlineAt)return failed(409,"REVIEW_WINDOW_CLOSED","The Journey review window has closed");const created=await tx.journeyReview.create({data:{tripId,...performed,rating:value.rating,comment:value.comment}});return{ok:true as const,value:{rating:created.rating,comment:created.comment,submittedAt:created.submittedAt},created:true}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2034")return failed(503,"REVIEW_CHANGED_CONCURRENTLY","Review state changed concurrently; try again");if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002"&&JSON.stringify(error.meta??{}).includes("JourneyReview"))return failed(409,"REVIEW_ALREADY_SUBMITTED","A review has already been submitted for this Journey");throw error}}

export async function getRoleReputation(db:Database,userId:string,performedRole:JourneyReviewRole,cursor?:string,limit=20){const now=await db.$queryRaw<Array<{now:Date}>>(Prisma.sql`SELECT CURRENT_TIMESTAMP AS now`).then(rows=>rows[0].now);const rows=await db.journeyReview.findMany({where:{revieweeId:userId,revieweeRole:performedRole},include:{reviewer:{select:{name:true}},trip:{select:{viewerId:true,operatorId:true,reviewDeadlineAt:true,reviews:{select:{reviewerId:true,revieweeId:true,reviewerRole:true,revieweeRole:true}}}}},orderBy:[{submittedAt:"desc"},{id:"desc"}]});const revealed=rows.filter(row=>{const pair=row.trip.reviews.filter(value=>validReview(value,row.trip));return validReview(row,row.trip)&&((pair.length===2&&new Set(pair.map(value=>value.reviewerRole)).size===2)||Boolean(row.trip.reviewDeadlineAt&&now>=row.trip.reviewDeadlineAt))});const average=revealed.length?revealed.reduce((sum,row)=>sum+row.rating,0)/revealed.length:null;const after=cursor?revealed.findIndex(row=>`${row.submittedAt.toISOString()}|${row.id}`===cursor)+1:0;const page=revealed.slice(after,after+Math.max(1,Math.min(limit,50)));return{average,count:revealed.length,comments:page.map(safeReview),nextCursor:after+page.length<revealed.length&&page.length?`${page.at(-1)!.submittedAt.toISOString()}|${page.at(-1)!.id}`:null}}
