import "server-only";

import { Prisma, PrismaClient, SafetyReportCategory, SafetyReportRole, SafetyReportSeverity, TripStatus } from "@prisma/client";

type Input={category?:unknown;severity?:unknown;narrative?:unknown};
type Code="INVALID_SAFETY_REPORT"|"JOURNEY_NOT_FOUND"|"JOURNEY_REPORT_UNSUPPORTED"|"SAFETY_REPORT_ALREADY_SUBMITTED"|"SAFETY_REPORT_CHANGED_CONCURRENTLY";
const fail=(status:400|404|409|503,code:Code,error:string)=>({ok:false as const,status,code,error});
const eligible=new Set<TripStatus>([TripStatus.ACCEPTED,TripStatus.IN_PROGRESS,TripStatus.ENDED,TripStatus.FEEDBACK_COMPLETED,TripStatus.CANCELLED]);
const normalize=(input:Input)=>{if(typeof input.category!=="string"||!Object.values(SafetyReportCategory).includes(input.category as SafetyReportCategory)||typeof input.severity!=="string"||!Object.values(SafetyReportSeverity).includes(input.severity as SafetyReportSeverity)||typeof input.narrative!=="string")return null;const narrative=input.narrative.trim();if(narrative.length<10||narrative.length>2000)return null;return{category:input.category as SafetyReportCategory,severity:input.severity as SafetyReportSeverity,narrative}};

export async function submitSafetyReport(db:PrismaClient,actorId:string,tripId:string,input:Input){const value=normalize(input);if(!value)return fail(400,"INVALID_SAFETY_REPORT","Choose a valid category and severity and provide 10 to 2,000 characters");try{return await db.$transaction(async tx=>{const trip=await tx.trip.findFirst({where:{id:tripId,OR:[{viewerId:actorId},{operatorId:actorId}]},select:{viewerId:true,operatorId:true,status:true}});if(!trip)return fail(404,"JOURNEY_NOT_FOUND","Journey not found");if(!trip.operatorId||trip.viewerId===trip.operatorId||!eligible.has(trip.status))return fail(409,"JOURNEY_REPORT_UNSUPPORTED","This Journey does not support safety reporting");const performed=trip.viewerId===actorId?{reporterId:trip.viewerId,reportedId:trip.operatorId,reporterRole:SafetyReportRole.EXPLORER,reportedRole:SafetyReportRole.TELEPORTER}:{reporterId:trip.operatorId,reportedId:trip.viewerId,reporterRole:SafetyReportRole.TELEPORTER,reportedRole:SafetyReportRole.EXPLORER};const created=await tx.safetyReport.create({data:{tripId,...performed,...value},select:{id:true,createdAt:true}});return{ok:true as const,value:created}},{isolationLevel:Prisma.TransactionIsolationLevel.Serializable})}catch(error){if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2002")return fail(409,"SAFETY_REPORT_ALREADY_SUBMITTED","A safety report has already been submitted for this Journey");if(error instanceof Prisma.PrismaClientKnownRequestError&&error.code==="P2034")return fail(503,"SAFETY_REPORT_CHANGED_CONCURRENTLY","Safety report state changed concurrently; try again");throw error}}
