"use client";

import { useCallback, useEffect, useState } from "react";
import { ActionLink, Button, MetadataList, Notice, StatePanel, StatusBadge, Surface } from "@/components/ui/primitives";

type AccessState = { role: string; accountStatus: string; explorer: boolean; teleporter: boolean; teleporterObligation: boolean };
type Destination = { id: string; name: string; city: string; active: boolean };
type Settings = { profile: null | { operatingArea: string | null; serviceRadiusKm: number | null; supportsCustom: boolean; languages: string[]; accessibilityCapabilities: string[]; durationOptions: number[]; pilotStatus: string }; destinationIds: string[]; destinations: Destination[]; complete: boolean; readiness: { eligible: boolean; code: string; message: string } };
type Summary = { access: AccessState; settings: Settings };

const list = (values: string[], empty: string) => values.length ? values.join(", ") : empty;
export default function TeleporterAccountOverview() {
  const [summary, setSummary] = useState<Summary | null>(null), [state, setState] = useState<"loading" | "ready" | "error">("loading"), [error, setError] = useState("");
  const load = useCallback(async () => { setState("loading"); setError(""); try { const [accessResponse, settingsResponse] = await Promise.all([fetch("/api/access-state", { cache: "no-store" }), fetch("/api/operator/settings", { cache: "no-store" })]); const access = await accessResponse.json(), settings = await settingsResponse.json(); if (!accessResponse.ok || !settingsResponse.ok) throw new Error(access.error ?? settings.error ?? "Account summary could not be loaded"); setSummary({ access, settings }); setState("ready"); } catch (value) { setError(value instanceof Error ? value.message : "Account summary could not be loaded"); setState("error"); } }, []);
  useEffect(() => { void load(); }, [load]);

  if (state === "loading") return <section className="mt-6" aria-labelledby="account-overview-heading"><h2 id="account-overview-heading" className="sr-only">Account overview</h2><StatePanel title="Loading account overview" busy><p role="status">Loading participation status, readiness, and service setup…</p></StatePanel></section>;
  if (state === "error" || !summary) return <section className="mt-6" aria-labelledby="account-overview-heading"><h2 id="account-overview-heading" className="sr-only">Account overview</h2><StatePanel title="Account overview could not be loaded" tone="danger" action={<Button variant="secondary" onClick={() => void load()}>Retry account overview</Button>}><p role="alert">{error}</p></StatePanel></section>;

  const { access, settings } = summary, profile = settings.profile;
  const destinations = settings.destinations.filter(destination => settings.destinationIds.includes(destination.id)).map(destination => `${destination.name}${destination.city ? `, ${destination.city}` : ""}`);
  return <>
    <Surface className="mt-6" aria-labelledby="account-overview-heading"><h2 id="account-overview-heading" className="text-heading-2">Account overview</h2><div className="mt-5 grid gap-4 sm:grid-cols-3"><div><p className="text-label text-ink-muted">Role</p><p className="mt-1">Teleporter</p></div><div><p className="text-label text-ink-muted">Account status</p><StatusBadge className="mt-1">{access.accountStatus}</StatusBadge></div><div><p className="text-label text-ink-muted">Pilot status</p><StatusBadge className="mt-1">{profile?.pilotStatus ?? "Not configured"}</StatusBadge></div></div><div className="mt-5 border-t border-line pt-5"><p className="text-label text-ink-muted">Operational readiness</p><p className="mt-1 font-semibold">{settings.readiness.eligible ? "Ready" : "Not ready"}</p><p className="mt-2 break-words text-body-sm text-ink-secondary">{settings.readiness.message}</p><p className="mt-2 text-caption text-ink-muted">Server code: {settings.readiness.code} · Required setup {settings.complete ? "complete" : "incomplete"}</p></div></Surface>
    <Surface className="mt-6" aria-labelledby="service-setup-heading"><div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><h2 id="service-setup-heading" className="text-heading-2">Service setup</h2><p className="mt-2 text-body-sm text-ink-secondary">Read-only summary of the capabilities configured through Teleporter Home.</p></div><ActionLink href="/operator" variant="secondary">Edit service setup on Home</ActionLink></div><MetadataList className="mt-5" items={[{ term: "Service area", detail: profile?.operatingArea || "Not configured" }, { term: "Planning radius", detail: profile?.serviceRadiusKm == null ? "Not configured" : `${profile.serviceRadiusKm} km` }, { term: "Destinations", detail: <span className="break-words">{list(destinations, "None selected")}</span> }, { term: "Languages", detail: <span className="break-words">{list(profile?.languages ?? [], "None selected")}</span> }, { term: "Accessibility support", detail: <span className="break-words">{list(profile?.accessibilityCapabilities ?? [], "None selected")}</span> }, { term: "Supported durations", detail: profile?.durationOptions?.length ? profile.durationOptions.map(value => `${value} minutes`).join(", ") : "None selected" }, { term: "Custom destination support", detail: profile?.supportsCustom ? "Supported" : "Not supported" }]} /></Surface>
    <Surface className="mt-6" aria-labelledby="application-heading"><h2 id="application-heading" className="text-heading-2">Teleporter application</h2><p className="mt-2 text-body-sm text-ink-secondary">Application history and available application actions remain in the existing Explorer application flow. Your current pilot status is <strong>{profile?.pilotStatus ?? "not configured"}</strong>.</p>{access.role === "VIEWER" ? <ActionLink href="/viewer/operator-application" variant="secondary" className="mt-4">Review application status</ActionLink> : <p className="mt-3 text-body-sm text-ink-muted">Application editing is not available for your current role.</p>}</Surface>
    {!settings.readiness.eligible && <Notice className="mt-6" variant="warning" role="status" title="Participation needs attention"><p>{settings.readiness.message}</p></Notice>}
  </>;
}
