import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { OperatorPilotStatus, PrismaClient, ProposalStatus, Role } from "@prisma/client";
import { acceptProposal, getExplorerAgreement, getTeleporterAgreement, listAdminAgreements } from "../lib/agreements";

if (!process.env.PHASE3_TEST_DATABASE_URL || !process.env.PHASE4_TEST_DATABASE_URL || process.env.PHASE3_TEST_DATABASE_URL !== process.env.PHASE4_TEST_DATABASE_URL || process.env.DATABASE_URL !== process.env.PHASE3_TEST_DATABASE_URL) throw new Error("Unsafe database mapping");
const db=new PrismaClient(),run=`p5a1-${randomUUID()}`,now=new Date(),plus=(minutes:number)=>new Date(now.getTime()+minutes*60_000);

async function fixture(windowed:boolean,operatorCount=1){
  const destination=await db.destination.create({data:{slug:`${run}-${randomUUID()}`,name:"Exact start test",shortDescription:"Disposable",city:"Test City",meetingArea:"Gate",category:"Test",durationOptions:[30],active:true}});
  const explorer=await db.user.create({data:{clerkId:`${run}-${randomUUID()}`,name:"Explorer",role:Role.VIEWER}}),operators=[];
  for(let i=0;i<operatorCount;i++)operators.push(await db.user.create({data:{clerkId:`${run}-${randomUUID()}`,name:`Teleporter ${i}`,role:Role.OPERATOR,operatorProfile:{create:{operatingArea:"Test City",serviceRadiusKm:10,languages:["English"],accessibilityCapabilities:[],durationOptions:[30],pilotStatus:OperatorPilotStatus.APPROVED}},destinationServices:{create:{destinationId:destination.id}}}}));
  const request=await db.journeyRequest.create({data:{explorerId:explorer.id,destinationId:destination.id,publicPlaceName:"Exact start test",coarseLocation:"Test City",earliestStart:plus(120),latestStart:plus(180),durationMinutes:30,proposedPriceMinor:2500,currency:"USD",expiresAt:plus(90)}}),proposals=[];
  for(const [i,operator] of operators.entries())proposals.push(await db.proposal.create({data:{journeyRequestId:request.id,teleporterId:operator.id,version:1,earliestStart:plus(120+i),latestStart:windowed?plus(150+i):null,durationMinutes:30,proposedPriceMinor:2500+i,currency:"USD",validUntil:plus(60)}}));
  return{destination,explorer,operators,request,proposals};
}
async function unchanged(requestId:string){assert.equal(await db.agreement.count({where:{journeyRequestId:requestId}}),0);assert.equal(await db.trip.count({where:{journeyRequest:{is:{id:requestId}}}}),0);const request=await db.journeyRequest.findUniqueOrThrow({where:{id:requestId},include:{proposals:true}});assert.equal(request.status,"OPEN");assert.ok(request.proposals.every(p=>p.status===ProposalStatus.ACTIVE));}
async function test(name:string,work:()=>Promise<void>){await work();console.log(`PASS ${name}`)}

async function main(){
  await test("fixed Proposal records earliestStart and preserves activeTripId",async()=>{const f=await fixture(false);const result=await acceptProposal(db,f.explorer.id,f.request.id,f.proposals[0].id,{},now);assert.equal(result.ok,true);if(!result.ok)return;assert.equal(result.value.agreedStartAt?.getTime(),f.proposals[0].earliestStart.getTime());assert.equal((await db.user.findUniqueOrThrow({where:{id:f.operators[0].id}})).activeTripId,result.value.tripId)});
  await test("fixed Proposal rejects alternate start without writes",async()=>{const f=await fixture(false);const result=await acceptProposal(db,f.explorer.id,f.request.id,f.proposals[0].id,{scheduledStartAt:plus(130).toISOString()},now);assert.equal(result.ok,false);if(!result.ok)assert.equal(result.status,400);await unchanged(f.request.id)});
  for(const boundary of ["earliest","latest"] as const)await test(`windowed Proposal accepts ${boundary} boundary`,async()=>{const f=await fixture(true),selected=boundary==="earliest"?f.proposals[0].earliestStart:f.proposals[0].latestStart!;const result=await acceptProposal(db,f.explorer.id,f.request.id,f.proposals[0].id,{scheduledStartAt:selected.toISOString()},now);assert.equal(result.ok,true);if(result.ok)assert.equal(result.value.agreedStartAt?.getTime(),selected.getTime())});
  for(const [name,input] of [["missing",{}],["before",{scheduledStartAt:plus(119).toISOString()}],["after",{scheduledStartAt:plus(151).toISOString()}],["malformed",{scheduledStartAt:"not-a-date"}],["offset-free",{scheduledStartAt:"2026-08-02T14:30:00"}],["unknown",{unexpected:true}]] as const)await test(`windowed Proposal rejects ${name} input without writes`,async()=>{const f=await fixture(true);const result=await acceptProposal(db,f.explorer.id,f.request.id,f.proposals[0].id,input,now);assert.equal(result.ok,false);if(!result.ok)assert.equal(result.status,400);await unchanged(f.request.id)});
  await test("same-Proposal retry preserves exact start",async()=>{const f=await fixture(true),first=f.proposals[0].earliestStart,second=f.proposals[0].latestStart!;const accepted=await acceptProposal(db,f.explorer.id,f.request.id,f.proposals[0].id,{scheduledStartAt:first.toISOString()},now);assert.equal(accepted.ok,true);const retry=await acceptProposal(db,f.explorer.id,f.request.id,f.proposals[0].id,{scheduledStartAt:second.toISOString()},now);assert.equal(retry.ok,true);if(retry.ok){assert.equal(retry.created,false);assert.equal(retry.value.agreedStartAt?.getTime(),first.getTime())}});
  await test("different-Proposal retry remains conflict",async()=>{const f=await fixture(true,2);assert.equal((await acceptProposal(db,f.explorer.id,f.request.id,f.proposals[0].id,{scheduledStartAt:f.proposals[0].earliestStart.toISOString()},now)).ok,true);const result=await acceptProposal(db,f.explorer.id,f.request.id,f.proposals[1].id,{scheduledStartAt:f.proposals[1].earliestStart.toISOString()},now);assert.equal(result.ok,false);if(!result.ok)assert.equal(result.status,409)});
  await test("forced transactional failure rolls back every acceptance write",async()=>{const f=await fixture(false);await db.$executeRawUnsafe(`CREATE OR REPLACE FUNCTION "phase5a1_force_conversion_failure"() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'forced Phase 5A.1 rollback'; END; $$ LANGUAGE plpgsql`);await db.$executeRawUnsafe(`CREATE TRIGGER "phase5a1_force_conversion_failure" BEFORE UPDATE ON "JourneyRequest" FOR EACH ROW WHEN (NEW."status" = 'CONVERTED') EXECUTE FUNCTION "phase5a1_force_conversion_failure"()`);try{await assert.rejects(acceptProposal(db,f.explorer.id,f.request.id,f.proposals[0].id,{},now));assert.equal(await db.agreement.count({where:{journeyRequestId:f.request.id}}),0);assert.equal(await db.trip.count({where:{journeyRequest:{is:{id:f.request.id}}}}),0);const request=await db.journeyRequest.findUniqueOrThrow({where:{id:f.request.id},include:{proposals:true}});assert.equal(request.status,"OPEN");assert.equal(request.tripId,null);assert.ok(request.proposals.every(p=>p.status===ProposalStatus.ACTIVE));assert.equal((await db.user.findUniqueOrThrow({where:{id:f.operators[0].id}})).activeTripId,null)}finally{await db.$executeRawUnsafe(`DROP TRIGGER IF EXISTS "phase5a1_force_conversion_failure" ON "JourneyRequest"`);await db.$executeRawUnsafe(`DROP FUNCTION IF EXISTS "phase5a1_force_conversion_failure"()`)}});
  await test("legacy null Agreement remains readable in all projections",async()=>{const f=await fixture(false);const accepted=await acceptProposal(db,f.explorer.id,f.request.id,f.proposals[0].id,{},now);assert.equal(accepted.ok,true);if(!accepted.ok)return;await db.$executeRawUnsafe(`ALTER TABLE "Agreement" DISABLE TRIGGER "Agreement_prevent_update"`);try{await db.agreement.update({where:{id:accepted.value.id},data:{agreedStartAt:null}})}finally{await db.$executeRawUnsafe(`ALTER TABLE "Agreement" ENABLE TRIGGER "Agreement_prevent_update"`)}const explorer=await getExplorerAgreement(db,f.explorer.id,f.request.id);const teleporter=await getTeleporterAgreement(db,f.operators[0].id,accepted.value.id);const admin=(await listAdminAgreements(db)).find(item=>item.id===accepted.value.id);for(const projected of [explorer,teleporter,admin])assert.equal(projected?.agreedStartAt,null);assert.ok(explorer&&!("explorerId" in explorer)&&!("teleporterId" in explorer));assert.ok(teleporter&&!("explorerId" in teleporter)&&!("teleporterId" in teleporter));assert.ok(admin&&("explorerId" in admin)&&("teleporterId" in admin))});
  await test("PostgreSQL rejects agreedStartAt update and existing update/delete",async()=>{const f=await fixture(false);const result=await acceptProposal(db,f.explorer.id,f.request.id,f.proposals[0].id,{},now);assert.equal(result.ok,true);if(!result.ok)return;await assert.rejects(db.agreement.update({where:{id:result.value.id},data:{agreedStartAt:plus(140)}}));await assert.rejects(db.agreement.update({where:{id:result.value.id},data:{agreedPriceMinor:2600}}));await assert.rejects(db.agreement.delete({where:{id:result.value.id}}))});
}
main().catch(error=>{console.error(error instanceof Error?error.message:error);process.exitCode=1}).finally(()=>db.$disconnect());
