import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { AdminRoleChangeAction, OperatorApplicationStatus, OperatorPilotStatus, PrismaClient, Role, TripStatus } from "@prisma/client";
import { assignViewerAsOperator } from "../lib/role-transitions";
import { getAdminOperatorApplication, listViewerOperatorApplications, reviewOperatorApplication, submitOperatorApplication, withdrawOperatorApplication } from "../lib/operator-applications";

if (process.env.PHASE5D_ACTIVE_SCHEMA !== "FULL" || process.env.PHASE5D_CONFIRM_DISPOSABLE_DATABASE !== "YES_DELETE_PHASE5D_TEST_DATA") throw new Error("Unsafe Phase 5D service integration mapping");
const db = new PrismaClient(); const run = `phase5d-service-${randomUUID()}`;
const body = (suffix: string) => ({ qualifications: `  Qualified for remote visitor support ${suffix}  `, relevantExperience: `  Relevant visitor experience ${suffix}  `, languages: ["English", "Portuguese"], availability: `  Weekday availability ${suffix}  `, supportingUrl: "https://example.test/evidence", additionalNote: "  Additional context  " });
async function user(suffix: string, role: Role = Role.VIEWER) { return db.user.create({ data: { clerkId: `${run}-${suffix}`, name: `Phase 5D ${suffix}`, role } }); }
async function pending(applicantId: string, suffix: string) { const result = await submitOperatorApplication(db, applicantId, body(suffix)); assert.equal(result.ok, true); if (!result.ok) throw new Error("Pending application fixture failed"); return result.value; }

async function main() { try {
  const admin = await user("admin", Role.ADMIN); const admin2 = await user("admin2", Role.ADMIN); const viewer = await user("viewer");
  const submitted = await pending(viewer.id, "submission"); assert.equal(submitted.qualifications, "Qualified for remote visitor support submission"); assert.equal(submitted.additionalNote, "Additional context");
  assert.equal((await db.user.findUniqueOrThrow({ where: { id: viewer.id } })).role, Role.VIEWER); assert.equal(await db.operatorProfile.count({ where: { userId: viewer.id } }), 0); assert.equal(await db.adminRoleChangeAudit.count({ where: { targetId: viewer.id } }), 0);
  const duplicate = await submitOperatorApplication(db, viewer.id, body("duplicate")); assert.equal(duplicate.ok, false); if (!duplicate.ok) assert.equal(duplicate.code, "PENDING_APPLICATION_EXISTS"); assert.equal(await db.operatorApplication.count({ where: { applicantId: viewer.id, status: OperatorApplicationStatus.PENDING } }), 1);
  const stranger = await user("stranger"); const notOwned = await withdrawOperatorApplication(db, stranger.id, submitted.id); assert.equal(notOwned.ok, false); if (!notOwned.ok) assert.equal(notOwned.code, "APPLICATION_NOT_OWNED");
  const withdrawn = await withdrawOperatorApplication(db, viewer.id, submitted.id, new Date("2026-06-01")); assert.equal(withdrawn.ok, true); if (withdrawn.ok) { assert.equal(withdrawn.value.status, OperatorApplicationStatus.WITHDRAWN); assert.ok(withdrawn.value.withdrawnAt); }
  const repeated = await withdrawOperatorApplication(db, viewer.id, submitted.id); assert.equal(repeated.ok, false); if (!repeated.ok) assert.equal(repeated.code, "APPLICATION_NOT_PENDING");
  const reapplied = await pending(viewer.id, "reapplication"); const history = await listViewerOperatorApplications(db, viewer.id); assert.equal(history.ok, true); if (history.ok) assert.deepEqual(history.value.map(value => value.id), [reapplied.id, submitted.id]);
  const rejected = await reviewOperatorApplication(db, admin.id, reapplied.id, { decision: "REJECTED", reviewNote: "  More experience requested  " }, new Date("2026-06-02")); assert.equal(rejected.ok, true); if (rejected.ok) { assert.equal(rejected.value.application.reviewNote, "More experience requested"); assert.equal(rejected.value.roleTransition, null); }
  assert.equal((await db.user.findUniqueOrThrow({ where: { id: viewer.id } })).role, Role.VIEWER); assert.equal(await db.adminRoleChangeAudit.count({ where: { targetId: viewer.id } }), 0); assert.equal((await reviewOperatorApplication(db, admin2.id, reapplied.id, { decision: "APPROVED" })).ok, false);

  const approvedViewer = await user("approved"); const approvedApplication = await pending(approvedViewer.id, "approval"); const directBlocked = await assignViewerAsOperator(db, admin.id, approvedViewer.id); assert.equal(directBlocked.ok, false); if (!directBlocked.ok) assert.equal(directBlocked.code, "PENDING_OPERATOR_APPLICATION_EXISTS");
  const approved = await reviewOperatorApplication(db, admin.id, approvedApplication.id, { decision: "APPROVED", reviewNote: "Approved" }, new Date("2026-06-03")); assert.equal(approved.ok, true);
  const approvedState = await db.user.findUniqueOrThrow({ where: { id: approvedViewer.id }, include: { operatorProfile: true } }); assert.equal(approvedState.role, Role.OPERATOR); assert.equal(approvedState.online, false); assert.equal(approvedState.operatorProfile?.pilotStatus, OperatorPilotStatus.PENDING);
  const audits = await db.adminRoleChangeAudit.findMany({ where: { targetId: approvedViewer.id } }); assert.equal(audits.length, 1); assert.equal(audits[0].actorId, admin.id); assert.equal(audits[0].action, AdminRoleChangeAction.ASSIGN_OPERATOR); assert.equal((await submitOperatorApplication(db, approvedViewer.id, body("forbidden"))).ok, false); assert.equal((await withdrawOperatorApplication(db, approvedViewer.id, approvedApplication.id)).ok, false);

  const suspended = await user("suspended"); await db.operatorProfile.create({ data: { userId: suspended.id, operatingArea: "Dormant", serviceRadiusKm: 1, languages: [], accessibilityCapabilities: [], durationOptions: [], pilotStatus: OperatorPilotStatus.SUSPENDED } }); const suspendedApplication = await pending(suspended.id, "suspended"); assert.equal((await reviewOperatorApplication(db, admin.id, suspendedApplication.id, { decision: "APPROVED" })).ok, true); assert.equal((await db.operatorProfile.findUniqueOrThrow({ where: { userId: suspended.id } })).pilotStatus, OperatorPilotStatus.PENDING);
  const directSuspended = await user("direct-suspended"); await db.operatorProfile.create({ data: { userId: directSuspended.id, operatingArea: "Dormant", serviceRadiusKm: 1, languages: [], accessibilityCapabilities: [], durationOptions: [], pilotStatus: OperatorPilotStatus.SUSPENDED } }); assert.equal((await assignViewerAsOperator(db, admin.id, directSuspended.id)).ok, true); assert.equal((await db.operatorProfile.findUniqueOrThrow({ where: { userId: directSuspended.id } })).pilotStatus, OperatorPilotStatus.SUSPENDED);

  const obligated = await user("obligated"); const obligationApplication = await pending(obligated.id, "obligation"); await db.trip.create({ data: { viewerId: obligated.id, destination: "Audit fixture", livekitRoom: `${run}-room`, status: TripStatus.REQUESTED } }); const obligationResult = await reviewOperatorApplication(db, admin.id, obligationApplication.id, { decision: "APPROVED" }); assert.equal(obligationResult.ok, false); if (!obligationResult.ok) assert.equal(obligationResult.code, "UNFINISHED_VIEWER_OBLIGATION"); const obligationState = await db.operatorApplication.findUniqueOrThrow({ where: { id: obligationApplication.id } }); assert.equal(obligationState.status, OperatorApplicationStatus.PENDING); assert.equal(obligationState.reviewedById, null); assert.equal((await db.user.findUniqueOrThrow({ where: { id: obligated.id } })).role, Role.VIEWER); assert.equal(await db.operatorProfile.count({ where: { userId: obligated.id } }), 0); assert.equal(await db.adminRoleChangeAudit.count({ where: { targetId: obligated.id } }), 0);

  const changed = await user("changed"); const changedApplication = await pending(changed.id, "changed"); await db.user.update({ where: { id: changed.id }, data: { role: Role.OPERATOR } }); const changedResult = await reviewOperatorApplication(db, admin.id, changedApplication.id, { decision: "APPROVED" }); assert.equal(changedResult.ok, false); if (!changedResult.ok) assert.equal(changedResult.code, "APPLICANT_NOT_VIEWER"); assert.equal((await db.operatorApplication.findUniqueOrThrow({ where: { id: changedApplication.id } })).status, OperatorApplicationStatus.PENDING); assert.equal(await db.adminRoleChangeAudit.count({ where: { targetId: changed.id } }), 0);

  const concurrent = await user("concurrent"); const concurrentApplication = await pending(concurrent.id, "concurrent-review"); const reviews = await Promise.all([reviewOperatorApplication(db, admin.id, concurrentApplication.id, { decision: "APPROVED" }), reviewOperatorApplication(db, admin2.id, concurrentApplication.id, { decision: "REJECTED" })]); assert.equal(reviews.filter(value => value.ok).length, 1); const final = await db.operatorApplication.findUniqueOrThrow({ where: { id: concurrentApplication.id } }); assert.notEqual(final.status, OperatorApplicationStatus.PENDING); assert.equal(await db.adminRoleChangeAudit.count({ where: { targetId: concurrent.id } }), final.status === OperatorApplicationStatus.APPROVED ? 1 : 0);
  const concurrentSubmitter = await user("concurrent-submit"); const submissions = await Promise.all([submitOperatorApplication(db, concurrentSubmitter.id, body("concurrent-a")), submitOperatorApplication(db, concurrentSubmitter.id, body("concurrent-b"))]); assert.equal(submissions.filter(value => value.ok).length, 1); assert.equal(await db.operatorApplication.count({ where: { applicantId: concurrentSubmitter.id, status: OperatorApplicationStatus.PENDING } }), 1);

  const viewerProjection = await listViewerOperatorApplications(db, viewer.id); assert.equal(viewerProjection.ok, true); if (viewerProjection.ok) assert.equal("reviewer" in viewerProjection.value[0], false); const adminProjection = await getAdminOperatorApplication(db, admin.id, reapplied.id); assert.equal(adminProjection.ok, true); if (adminProjection.ok) { assert.equal("email" in (adminProjection.value.applicant ?? {}), false); assert.equal("audit" in adminProjection.value, false); }
  console.log("Phase 5D service workflow PostgreSQL integration assertions passed.");
 } finally { await db.trip.deleteMany({ where: { viewer: { clerkId: { startsWith: run } } } }); await db.adminRoleChangeAudit.deleteMany({ where: { OR: [{ actor: { clerkId: { startsWith: run } } }, { target: { clerkId: { startsWith: run } } }] } }); await db.operatorApplication.deleteMany({ where: { applicant: { clerkId: { startsWith: run } } } }); await db.operatorDestination.deleteMany({ where: { operator: { clerkId: { startsWith: run } } } }); await db.operatorProfile.deleteMany({ where: { user: { clerkId: { startsWith: run } } } }); await db.user.deleteMany({ where: { clerkId: { startsWith: run } } }); assert.equal(await db.user.count({ where: { clerkId: { startsWith: run } } }), 0); await db.$disconnect(); }
}
void main().catch(error=>{console.error(error instanceof Error?error.message:"Phase 5D service database integration failed");process.exitCode=1});
