import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { AccountStatus, PrismaClient, Role, TripStatus } from "@prisma/client";
import { getSimulatedTipState, submitSimulatedTip } from "../lib/simulated-tips";
const db=new PrismaClient(),run=`tip-${randomUUID()}`,pass=(s:string)=>console.log(`PASS ${s}`);
async function user(name:string,status:AccountStatus=AccountStatus.ACTIVE){return db.user.create({data:{clerkId:`${run}-${randomUUID()}`,name,role:Role.VIEWER,accountStatus:status}})}
async function trip(viewerId:string,operatorId:string|null,status:TripStatus=TripStatus.ENDED,immediate=true){return db.trip.create({data:{viewerId,operatorId,destination:"Tip test",livekitRoom:`${run}-${randomUUID()}`,status,immediate,...(status===TripStatus.ENDED||status===TripStatus.FEEDBACK_COMPLETED?{endedAt:new Date()}:{} )}})}
async function main(){
 const explorer=await user("Explorer"),teleporter=await user("Teleporter"),stranger=await user("Stranger");
 for(const immediate of[true,false]){const journey=await trip(explorer.id,teleporter.id,TripStatus.ENDED,immediate),result=await submitSimulatedTip(db,explorer.id,journey.id,{amountMinor:500});assert.ok(result.ok&&result.created);assert.equal(result.ok&&result.value.currency,"USD");assert.equal((await getSimulatedTipState(db,teleporter.id,journey.id)).ok,true)}pass("completed immediate and scheduled Journeys create USD receipts visible to both participants");
 const historical=await trip(explorer.id,teleporter.id,TripStatus.FEEDBACK_COMPLETED);assert.equal((await getSimulatedTipState(db,explorer.id,historical.id)).ok,true);assert.equal(await db.simulatedTip.count({where:{tripId:historical.id}}),0);pass("historical Journey is eligible without fabricated Tip");
 for(const status of[TripStatus.REQUESTED,TripStatus.IN_PROGRESS,TripStatus.CANCELLED])assert.equal((await submitSimulatedTip(db,explorer.id,(await trip(explorer.id,teleporter.id,status)).id,{amountMinor:500})).ok,false);pass("incomplete Journeys reject");
 const denied=await trip(explorer.id,teleporter.id);for(const actor of[teleporter.id,stranger.id]){const result=await submitSimulatedTip(db,actor,denied.id,{amountMinor:500});assert.equal(result.ok,false);if(!result.ok)assert.equal(result.code,"JOURNEY_NOT_FOUND")}assert.equal((await getSimulatedTipState(db,stranger.id,denied.id)).ok,false);pass("Teleporter and unrelated submission is denied privately");
 for(const bad of[undefined,0,501,1000.5,"500",null])assert.equal((await submitSimulatedTip(db,explorer.id,(await trip(explorer.id,teleporter.id)).id,{amountMinor:bad})).ok,false);pass("only preset integer amounts are accepted");
 const retry=await trip(explorer.id,teleporter.id),first=await submitSimulatedTip(db,explorer.id,retry.id,{amountMinor:1000}),same=await submitSimulatedTip(db,explorer.id,retry.id,{amountMinor:1000}),changed=await submitSimulatedTip(db,explorer.id,retry.id,{amountMinor:1500});assert.ok(first.ok&&first.created&&same.ok&&!same.created&&!changed.ok);if(!changed.ok)assert.equal(changed.code,"SIMULATED_TIP_ALREADY_SUBMITTED");pass("same retry is idempotent and changed retry conflicts");
 const inactive=await user("Inactive",AccountStatus.DEACTIVATED),inactiveTrip=await trip(inactive.id,teleporter.id);assert.equal((await submitSimulatedTip(db,inactive.id,inactiveTrip.id,{amountMinor:500})).ok,false);assert.equal((await getSimulatedTipState(db,inactive.id,inactiveTrip.id)).ok,true);pass("inactive Explorer reads but cannot submit");
 await assert.rejects(db.simulatedTip.create({data:{tripId:(await trip(explorer.id,teleporter.id)).id,explorerId:stranger.id,teleporterId:teleporter.id,amountMinor:500,currency:"USD"}}));for(const amountMinor of[1,501,2500])await assert.rejects(db.simulatedTip.create({data:{tripId:(await trip(explorer.id,teleporter.id)).id,explorerId:explorer.id,teleporterId:teleporter.id,amountMinor,currency:"USD"}}));await assert.rejects(db.simulatedTip.create({data:{tripId:(await trip(explorer.id,teleporter.id)).id,explorerId:explorer.id,teleporterId:teleporter.id,amountMinor:500,currency:"EUR"}}));const immutable=await db.simulatedTip.findFirstOrThrow({where:{explorerId:explorer.id}});await assert.rejects(db.simulatedTip.update({where:{id:immutable.id},data:{amountMinor:2000}}));await assert.rejects(db.simulatedTip.delete({where:{id:immutable.id}}));pass("database enforces attribution, values and immutability");
 const concurrent=await trip(explorer.id,teleporter.id),a=new PrismaClient(),b=new PrismaClient(),outcomes=await Promise.all([submitSimulatedTip(a,explorer.id,concurrent.id,{amountMinor:2000}),submitSimulatedTip(b,explorer.id,concurrent.id,{amountMinor:2000})]);assert.equal(outcomes.filter(x=>x.ok).length,2);assert.equal(await db.simulatedTip.count({where:{tripId:concurrent.id}}),1);await a.$disconnect();await b.$disconnect();
 const different=await trip(explorer.id,teleporter.id),c=new PrismaClient(),d=new PrismaClient(),mixed=await Promise.all([submitSimulatedTip(c,explorer.id,different.id,{amountMinor:500}),submitSimulatedTip(d,explorer.id,different.id,{amountMinor:1000})]);assert.equal(mixed.filter(x=>x.ok).length,1);assert.equal(await db.simulatedTip.count({where:{tripId:different.id}}),1);await c.$disconnect();await d.$disconnect();pass("independent concurrency leaves exactly one row");
}main().finally(()=>db.$disconnect());
