import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { OperatorPilotStatus, PrismaClient, Role, ScheduledJourneyRescheduleStatus, ScheduledJourneyReservationStatus, TripStatus } from "@prisma/client";
import { acceptProposal, getExplorerAgreement, getTeleporterAgreement, listAdminAgreements } from "../lib/agreements";
import { acceptRescheduleProposal, createRescheduleProposal, declineRescheduleProposal, getReschedulingState, listPendingRescheduleProposals, withdrawRescheduleProposal } from "../lib/rescheduling";
import { cancelTrip, endTrip, startTrip } from "../lib/trip-lifecycle";

if (!process.env.PHASE3_TEST_DATABASE_URL || !process.env.PHASE4_TEST_DATABASE_URL || process.env.PHASE3_TEST_DATABASE_URL !== process.env.PHASE4_TEST_DATABASE_URL || process.env.DATABASE_URL !== process.env.PHASE3_TEST_DATABASE_URL) throw new Error("Unsafe database mapping");
const db = new PrismaClient(), run = `p5b-rs-${randomUUID()}`;
const now = new Date("2100-01-01T00:00:00.000Z"), origin = new Date("2100-02-01T00:00:00.000Z"), at = (m: number) => new Date(origin.getTime() + m * 60_000);
async function test(name: string, work: () => Promise<void>) { await work(); console.log(`PASS ${name}`); }
async function base() { const destination = await db.destination.create({ data: { slug: `${run}-${randomUUID()}`, name: "Reschedule", shortDescription: "Disposable", city: "Test City", meetingArea: "Gate", category: "Test", durationOptions: [30], active: true } }); const teleporter = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, name: "Teleporter", role: Role.OPERATOR, operatorProfile: { create: { operatingArea: "Test City", serviceRadiusKm: 10, languages: ["English"], accessibilityCapabilities: [], durationOptions: [30], pilotStatus: OperatorPilotStatus.APPROVED } }, destinationServices: { create: { destinationId: destination.id } } } }); return { destination, teleporter }; }
async function scheduled(sharedValue?: Awaited<ReturnType<typeof base>>, start = at(120)) { const shared = sharedValue ?? await base(); const explorer = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, role: Role.VIEWER } }); const request = await db.journeyRequest.create({ data: { explorerId: explorer.id, destinationId: shared.destination.id, publicPlaceName: "Reschedule", coarseLocation: "Test City", earliestStart: start, latestStart: new Date(start.getTime() + 30 * 60_000), durationMinutes: 30, proposedPriceMinor: 2500, currency: "USD", expiresAt: new Date(start.getTime() - 60_000) } }); const proposal = await db.proposal.create({ data: { journeyRequestId: request.id, teleporterId: shared.teleporter.id, version: 1, earliestStart: start, durationMinutes: 30, proposedPriceMinor: 2500, currency: "USD", validUntil: new Date(start.getTime() - 30_000) } }); const accepted = await acceptProposal(db, explorer.id, request.id, proposal.id, {}, now); assert.equal(accepted.ok, true); if (!accepted.ok) throw new Error("accept failed"); const trip = await db.trip.findUniqueOrThrow({ where: { id: accepted.value.tripId } }); const reservation = await db.scheduledJourneyReservation.findFirstOrThrow({ where: { tripId: trip.id, status: "CONFIRMED" } }); return { ...shared, explorer, request, agreement: accepted.value, trip, reservation }; }
const propose = (v: Awaited<ReturnType<typeof scheduled>>, actor: string, start = at(300), end = at(330)) => createRescheduleProposal(db, actor, v.trip.id, { proposedStartAt: start.toISOString(), proposedEndAt: end.toISOString() }, now);
async function amendment(v: Awaited<ReturnType<typeof scheduled>>, actor = v.explorer.id, start = at(300), end = at(330)) { const result = await propose(v, actor, start, end); assert.equal(result.ok, true); if (!result.ok) throw new Error("proposal failed"); return result.value; }
async function reservations(v: Awaited<ReturnType<typeof scheduled>>) { return db.scheduledJourneyReservation.findMany({ where: { tripId: v.trip.id }, orderBy: { createdAt: "asc" } }); }

async function main() {
  await test("authorized UI projection derives eligibility and confirmed interval", async () => { const v = await scheduled(); for (const actor of [v.explorer.id, v.teleporter.id]) { const result = await getReschedulingState(db, actor, v.trip.id); assert.equal(result.ok, true); if (!result.ok) continue; assert.equal(result.value.eligible, true); assert.equal(result.value.canPropose, true); assert.equal(result.value.currentStartAt?.getTime(), v.reservation.startAt.getTime()); assert.equal(result.value.currentEndAt?.getTime(), v.reservation.endAt.getTime()); assert.equal(result.value.durationMinutes, 30); assert.equal(result.value.proposal, null); } const stranger = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, role: Role.VIEWER } }); assert.equal((await getReschedulingState(db, stranger.id, v.trip.id)).ok, false); });
  await test("Explorer proposes and Teleporter views and accepts", async () => { const v = await scheduled(); const p = await amendment(v); const visible = await listPendingRescheduleProposals(db, v.teleporter.id, v.trip.id); assert.equal(visible.ok, true); assert.equal(visible.ok && visible.value?.id, p.id); assert.equal((await acceptRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, now)).ok, true); const rows = await reservations(v); assert.deepEqual(rows.map(r => r.status), ["RELEASED", "CONFIRMED"]); assert.equal(rows[0].releasedAt?.getTime(), now.getTime()); const explorer = await getExplorerAgreement(db, v.explorer.id, v.request.id); const teleporter = await getTeleporterAgreement(db, v.teleporter.id, v.agreement.id); const admin = (await listAdminAgreements(db)).find(value => value.id === v.agreement.id); for (const projection of [explorer, teleporter, admin]) assert.equal(projection?.agreedStartAt?.getTime(), at(300).getTime()); });
  await test("Teleporter proposes and Explorer accepts", async () => { const v = await scheduled(); const p = await amendment(v, v.teleporter.id); assert.equal((await acceptRescheduleProposal(db, v.explorer.id, v.trip.id, p.id, now)).ok, true); });
  await test("proposer cannot self-accept", async () => { const v = await scheduled(); const p = await amendment(v); const result = await acceptRescheduleProposal(db, v.explorer.id, v.trip.id, p.id, now); assert.equal(result.ok, false); });
  await test("unrelated parties cannot view create accept decline or withdraw", async () => { const v = await scheduled(); const p = await amendment(v); const stranger = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, role: Role.VIEWER } }); assert.equal((await listPendingRescheduleProposals(db, stranger.id, v.trip.id)).ok, false); assert.equal((await propose(v, stranger.id)).ok, false); assert.equal((await acceptRescheduleProposal(db, stranger.id, v.trip.id, p.id, now)).ok, false); assert.equal((await declineRescheduleProposal(db, stranger.id, v.trip.id, p.id, now)).ok, false); assert.equal((await withdrawRescheduleProposal(db, stranger.id, v.trip.id, p.id, now)).ok, false); });
  await test("decline preserves current schedule", async () => { const v = await scheduled(); const p = await amendment(v); assert.equal((await declineRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, now)).ok, true); assert.deepEqual(await reservations(v), [v.reservation]); });
  await test("withdraw preserves current schedule", async () => { const v = await scheduled(); const p = await amendment(v); assert.equal((await withdrawRescheduleProposal(db, v.explorer.id, v.trip.id, p.id, now)).ok, true); assert.deepEqual(await reservations(v), [v.reservation]); });
  await test("duplicate creation is idempotent and one competing pending is rejected", async () => { const v = await scheduled(); const first = await propose(v, v.explorer.id); const retry = await propose(v, v.explorer.id); assert.equal(first.ok && retry.ok && first.value.id === retry.value.id && retry.created === false, true); assert.equal((await propose(v, v.teleporter.id, at(400), at(430))).ok, false); assert.equal(await db.scheduledJourneyRescheduleProposal.count({ where: { tripId: v.trip.id, status: "PENDING" } }), 1); });
  await test("invalid past same immediate and terminal Journeys are rejected", async () => { const v = await scheduled(); assert.equal((await createRescheduleProposal(db, v.explorer.id, v.trip.id, { proposedStartAt: "bad", proposedEndAt: at(300).toISOString() }, now)).ok, false); assert.equal((await propose(v, v.explorer.id, new Date(now.getTime() - 1), at(300))).ok, false); assert.equal((await propose(v, v.explorer.id, v.reservation.startAt, v.reservation.endAt)).ok, false); await db.trip.update({ where: { id: v.trip.id }, data: { status: TripStatus.CANCELLED } }); assert.equal((await propose(v, v.explorer.id)).ok, false); });
  await test("UI projection hides immediate terminal legacy and malformed controls", async () => { const immediate = await scheduled(); await db.trip.update({ where: { id: immediate.trip.id }, data: { immediate: true } }); const immediateState = await getReschedulingState(db, immediate.explorer.id, immediate.trip.id); assert.equal(immediateState.ok && immediateState.value.eligible, false); const terminal = await scheduled(); await db.trip.update({ where: { id: terminal.trip.id }, data: { status: TripStatus.ENDED } }); const terminalState = await getReschedulingState(db, terminal.explorer.id, terminal.trip.id); assert.equal(terminalState.ok && terminalState.value.eligible, false); const legacy = await scheduled(); await db.scheduledJourneyReservation.deleteMany({ where: { tripId: legacy.trip.id } }); const legacyState = await getReschedulingState(db, legacy.explorer.id, legacy.trip.id); assert.equal(legacyState.ok && legacyState.value.eligible, false); assert.equal(legacyState.ok && legacyState.value.currentStartAt?.getTime(), legacy.agreement.agreedStartAt?.getTime()); });
  await test("accepted replacement is authoritative for start", async () => { const v = await scheduled(); const p = await amendment(v, v.explorer.id, at(600), at(630)); await acceptRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, now); assert.equal((await startTrip(db, v.teleporter.id, Role.OPERATOR, v.trip.id, new Date(at(600).getTime() - 1))).ok, false); assert.equal((await startTrip(db, v.teleporter.id, Role.OPERATOR, v.trip.id, at(600))).ok, true); });
  await test("subsequent cancellation releases replacement only", async () => { const v = await scheduled(); const p = await amendment(v); await acceptRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, now); await cancelTrip(db, v.explorer.id, Role.VIEWER, v.trip.id, now); const rows = await reservations(v); assert.equal(rows.every(r => r.status === ScheduledJourneyReservationStatus.RELEASED), true); assert.equal(rows[0].releasedAt?.getTime(), now.getTime()); assert.equal(rows[1].releasedAt?.getTime(), now.getTime()); });
  await test("normal completion keeps replacement confirmed", async () => { const v = await scheduled(); const p = await amendment(v); await acceptRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, now); await startTrip(db, v.teleporter.id, Role.OPERATOR, v.trip.id, at(300)); await endTrip(db, v.teleporter.id, Role.OPERATOR, v.trip.id, at(330)); const rows = await reservations(v); assert.equal(rows[1].status, ScheduledJourneyReservationStatus.CONFIRMED); assert.equal(rows[1].releasedAt, null); });
  await test("old interval rebooks new overlap blocks and adjacency succeeds", async () => { const shared = await base(); const v = await scheduled(shared, at(120)); const p = await amendment(v, v.explorer.id, at(300), at(330)); await acceptRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, now); assert.equal((await scheduled(shared, at(120))).reservation.status, ScheduledJourneyReservationStatus.CONFIRMED); await assert.rejects(scheduled(shared, at(310))); assert.equal((await scheduled(shared, at(330))).reservation.status, ScheduledJourneyReservationStatus.CONFIRMED); });
  await test("forced replacement failure rolls back all mutations", async () => { const v = await scheduled(); const p = await amendment(v); await db.$executeRawUnsafe(`CREATE OR REPLACE FUNCTION "phase5b_force_replacement_failure"() RETURNS trigger AS $$ BEGIN IF NEW."startAt" = '${at(300).toISOString()}'::timestamptz THEN RAISE EXCEPTION 'forced replacement'; END IF; RETURN NEW; END; $$ LANGUAGE plpgsql`); await db.$executeRawUnsafe(`CREATE TRIGGER "phase5b_force_replacement_failure" BEFORE INSERT ON "ScheduledJourneyReservation" FOR EACH ROW EXECUTE FUNCTION "phase5b_force_replacement_failure"()`); try { await assert.rejects(acceptRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, now)); assert.deepEqual((await reservations(v)).map(r => r.status), ["CONFIRMED"]); assert.equal((await db.scheduledJourneyRescheduleProposal.findUniqueOrThrow({ where: { id: p.id } })).status, ScheduledJourneyRescheduleStatus.PENDING); } finally { await db.$executeRawUnsafe(`DROP TRIGGER IF EXISTS "phase5b_force_replacement_failure" ON "ScheduledJourneyReservation"`); await db.$executeRawUnsafe(`DROP FUNCTION IF EXISTS "phase5b_force_replacement_failure"()`); } });
  await test("duplicate acceptance preserves one replacement and timestamps", async () => { const v = await scheduled(); const p = await amendment(v); const first = await acceptRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, now); const retry = await acceptRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, at(500)); assert.equal(first.ok && retry.ok, true); assert.equal((await reservations(v)).length, 2); const saved = await db.scheduledJourneyRescheduleProposal.findUniqueOrThrow({ where: { id: p.id } }); assert.equal(saved.resolvedAt?.getTime(), now.getTime()); assert.equal((await reservations(v))[0].releasedAt?.getTime(), now.getTime()); });
  await test("declined and withdrawn proposals cannot later be accepted", async () => { for (const action of ["decline", "withdraw"] as const) { const v = await scheduled(); const p = await amendment(v); if (action === "decline") await declineRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, now); else await withdrawRescheduleProposal(db, v.explorer.id, v.trip.id, p.id, now); assert.equal((await acceptRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, now)).ok, false); } });
  await test("acceptance versus start has one coherent winner", async () => { const v = await scheduled(); const p = await amendment(v); await Promise.allSettled([acceptRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, now), startTrip(db, v.teleporter.id, Role.OPERATOR, v.trip.id, v.reservation.startAt)]); const trip = await db.trip.findUniqueOrThrow({ where: { id: v.trip.id } }); const rows = await reservations(v); assert.equal((trip.status === TripStatus.IN_PROGRESS && rows.length === 1 && rows[0].status === "CONFIRMED") || (trip.status === TripStatus.ACCEPTED && rows.length === 2 && rows[1].status === "CONFIRMED"), true); });
  await test("acceptance versus cancellation has one coherent winner", async () => { const v = await scheduled(); const p = await amendment(v); await Promise.allSettled([acceptRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, now), cancelTrip(db, v.explorer.id, Role.VIEWER, v.trip.id, now)]); const trip = await db.trip.findUniqueOrThrow({ where: { id: v.trip.id } }); const confirmed = await db.scheduledJourneyReservation.count({ where: { tripId: v.trip.id, status: "CONFIRMED" } }); assert.equal(trip.status === TripStatus.CANCELLED ? confirmed === 0 : confirmed === 1, true); });
  await test("accept decline and withdrawal races resolve once", async () => { for (const other of ["decline", "withdraw"] as const) { const v = await scheduled(); const p = await amendment(v); await Promise.allSettled([acceptRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, now), other === "decline" ? declineRescheduleProposal(db, v.teleporter.id, v.trip.id, p.id, now) : withdrawRescheduleProposal(db, v.explorer.id, v.trip.id, p.id, now)]); const saved = await db.scheduledJourneyRescheduleProposal.findUniqueOrThrow({ where: { id: p.id } }); assert.ok(["ACCEPTED", "DECLINED", "WITHDRAWN"].includes(saved.status)); assert.equal(await db.scheduledJourneyReservation.count({ where: { tripId: v.trip.id, status: "CONFIRMED" } }), 1); } });
  await test("cross-Trip reservation and activeTripId isolation", async () => { const shared = await base(); const first = await scheduled(shared, at(120)), second = await scheduled(shared, at(600)); const p = await amendment(first); await db.user.update({ where: { id: shared.teleporter.id }, data: { activeTripId: second.trip.id } }); await acceptRescheduleProposal(db, shared.teleporter.id, first.trip.id, p.id, now); assert.equal((await db.user.findUniqueOrThrow({ where: { id: shared.teleporter.id } })).activeTripId, second.trip.id); assert.equal((await db.scheduledJourneyReservation.findFirstOrThrow({ where: { tripId: second.trip.id, status: "CONFIRMED" } })).startAt.getTime(), at(600).getTime()); });
}
main().catch(error => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; }).finally(() => db.$disconnect());
