import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { OperatorPilotStatus, PrismaClient, ProposalStatus, Role, ScheduledJourneyReservationStatus, TripStatus } from "@prisma/client";
import { acceptProposal } from "../lib/agreements";
import { cancelTrip, endTrip, recoverStaleTrips, startTrip } from "../lib/trip-lifecycle";

if (!process.env.PHASE3_TEST_DATABASE_URL || !process.env.PHASE4_TEST_DATABASE_URL || process.env.PHASE3_TEST_DATABASE_URL !== process.env.PHASE4_TEST_DATABASE_URL || process.env.DATABASE_URL !== process.env.PHASE3_TEST_DATABASE_URL) throw new Error("Unsafe database mapping");
const db = new PrismaClient();
const run = `p5a4-${randomUUID()}`;
const decisionTime = new Date("2026-08-01T12:00:00.000Z");
const origin = new Date("2026-10-01T12:00:00.000Z");
const at = (minutes: number) => new Date(origin.getTime() + minutes * 60_000);
async function test(name: string, work: () => Promise<void>) { await work(); console.log(`PASS ${name}`); }

async function setup() {
  const destination = await db.destination.create({ data: { slug: `${run}-${randomUUID()}`, name: "Release lifecycle", shortDescription: "Disposable", city: "Test City", meetingArea: "Gate", category: "Test", durationOptions: [30], active: true } });
  const teleporter = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, name: "Release Teleporter", role: Role.OPERATOR, operatorProfile: { create: { operatingArea: "Test City", serviceRadiusKm: 10, languages: ["English"], accessibilityCapabilities: [], durationOptions: [30], pilotStatus: OperatorPilotStatus.APPROVED } }, destinationServices: { create: { destinationId: destination.id } } } });
  return { destination, teleporter };
}
async function fixture(base: Awaited<ReturnType<typeof setup>>, start = at(120), duration = 30) {
  const explorer = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, role: Role.VIEWER } });
  const request = await db.journeyRequest.create({ data: { explorerId: explorer.id, destinationId: base.destination.id, publicPlaceName: "Release lifecycle", coarseLocation: "Test City", earliestStart: start, latestStart: new Date(start.getTime() + 30 * 60_000), durationMinutes: duration, proposedPriceMinor: 2500, currency: "USD", expiresAt: new Date(start.getTime() - 60_000) } });
  const proposal = await db.proposal.create({ data: { journeyRequestId: request.id, teleporterId: base.teleporter.id, version: 1, earliestStart: start, durationMinutes: duration, proposedPriceMinor: 2500, currency: "USD", validUntil: new Date(start.getTime() - 30_000) } });
  return { ...base, explorer, request, proposal, start };
}
async function accepted(value: Awaited<ReturnType<typeof fixture>>) {
  const result = await acceptProposal(db, value.explorer.id, value.request.id, value.proposal.id, {}, decisionTime); assert.equal(result.ok, true); if (!result.ok) throw new Error("acceptance failed");
  return { ...value, agreement: result.value, trip: await db.trip.findUniqueOrThrow({ where: { id: result.value.tripId } }), reservation: await db.scheduledJourneyReservation.findUniqueOrThrow({ where: { agreementId: result.value.id } }) };
}
async function state(value: Awaited<ReturnType<typeof accepted>>) { return { trip: await db.trip.findUniqueOrThrow({ where: { id: value.trip.id } }), reservation: await db.scheduledJourneyReservation.findUniqueOrThrow({ where: { id: value.reservation.id } }), agreement: await db.agreement.findUniqueOrThrow({ where: { id: value.agreement.id } }) }; }

async function main() {
  await test("Viewer cancellation releases the future reservation and preserves relationships", async () => { const value = await accepted(await fixture(await setup())); assert.equal((await cancelTrip(db, value.explorer.id, Role.VIEWER, value.trip.id, decisionTime)).ok, true); const final = await state(value); assert.equal(final.trip.status, TripStatus.CANCELLED); assert.equal(final.reservation.status, ScheduledJourneyReservationStatus.RELEASED); assert.equal(final.reservation.releasedAt?.getTime(), decisionTime.getTime()); assert.equal(final.reservation.tripId, final.trip.id); assert.equal(final.reservation.agreementId, final.agreement.id); });
  await test("Teleporter cancellation releases the future reservation", async () => { const value = await accepted(await fixture(await setup())); assert.equal((await cancelTrip(db, value.teleporter.id, Role.OPERATOR, value.trip.id, decisionTime)).ok, true); assert.equal((await state(value)).reservation.status, ScheduledJourneyReservationStatus.RELEASED); });
  await test("released interval can be booked again while another confirmed overlap remains blocked", async () => { const base = await setup(); const released = await accepted(await fixture(base, at(120))); const blocking = await accepted(await fixture(base, at(240))); await cancelTrip(db, released.explorer.id, Role.VIEWER, released.trip.id, decisionTime); const replacement = await fixture(base, at(120)); assert.equal((await acceptProposal(db, replacement.explorer.id, replacement.request.id, replacement.proposal.id, {}, decisionTime)).ok, true); const overlap = await fixture(base, at(250)); const conflict = await acceptProposal(db, overlap.explorer.id, overlap.request.id, overlap.proposal.id, {}, decisionTime); assert.equal(conflict.ok, false); if (!conflict.ok) assert.equal(conflict.error, "The Teleporter is no longer available for the selected Journey time."); assert.equal((await state(blocking)).reservation.status, ScheduledJourneyReservationStatus.CONFIRMED); });
  await test("adjacent confirmed reservation remains valid after release", async () => { const base = await setup(); const first = await accepted(await fixture(base, at(120))); await accepted(await fixture(base, at(150))); await cancelTrip(db, first.explorer.id, Role.VIEWER, first.trip.id, decisionTime); assert.equal(await db.scheduledJourneyReservation.count({ where: { teleporterId: base.teleporter.id, status: ScheduledJourneyReservationStatus.CONFIRMED } }), 1); });
  await test("duplicate cancellation preserves the original releasedAt", async () => { const value = await accepted(await fixture(await setup())); assert.equal((await cancelTrip(db, value.explorer.id, Role.VIEWER, value.trip.id, decisionTime)).ok, true); assert.equal((await cancelTrip(db, value.explorer.id, Role.VIEWER, value.trip.id, at(500))).ok, true); assert.equal((await state(value)).reservation.releasedAt?.getTime(), decisionTime.getTime()); });
  await test("forced release failure rolls back cancellation and pointer clearing", async () => { const value = await accepted(await fixture(await setup())); await db.user.update({ where: { id: value.teleporter.id }, data: { activeTripId: value.trip.id } }); await db.$executeRawUnsafe(`CREATE OR REPLACE FUNCTION "phase5a4_force_release_failure"() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'forced release failure'; END; $$ LANGUAGE plpgsql`); await db.$executeRawUnsafe(`CREATE TRIGGER "phase5a4_force_release_failure" BEFORE UPDATE ON "ScheduledJourneyReservation" FOR EACH ROW WHEN (NEW."status" = 'RELEASED') EXECUTE FUNCTION "phase5a4_force_release_failure"()`); try { await assert.rejects(cancelTrip(db, value.explorer.id, Role.VIEWER, value.trip.id, decisionTime)); const final = await state(value); assert.equal(final.trip.status, TripStatus.ACCEPTED); assert.equal(final.reservation.status, ScheduledJourneyReservationStatus.CONFIRMED); assert.equal((await db.user.findUniqueOrThrow({ where: { id: value.teleporter.id } })).activeTripId, value.trip.id); } finally { await db.$executeRawUnsafe(`DROP TRIGGER IF EXISTS "phase5a4_force_release_failure" ON "ScheduledJourneyReservation"`); await db.$executeRawUnsafe(`DROP FUNCTION IF EXISTS "phase5a4_force_release_failure"()`); } });
  await test("unrelated release database error is not an availability conflict", async () => { const value = await accepted(await fixture(await setup())); await db.$executeRawUnsafe(`CREATE OR REPLACE FUNCTION "phase5a4_unrelated_failure"() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'unrelated release failure'; END; $$ LANGUAGE plpgsql`); await db.$executeRawUnsafe(`CREATE TRIGGER "phase5a4_unrelated_failure" BEFORE UPDATE ON "ScheduledJourneyReservation" FOR EACH ROW EXECUTE FUNCTION "phase5a4_unrelated_failure"()`); try { await assert.rejects(cancelTrip(db, value.explorer.id, Role.VIEWER, value.trip.id, decisionTime), error => error instanceof Error && !error.message.includes("no longer available")); } finally { await db.$executeRawUnsafe(`DROP TRIGGER IF EXISTS "phase5a4_unrelated_failure" ON "ScheduledJourneyReservation"`); await db.$executeRawUnsafe(`DROP FUNCTION IF EXISTS "phase5a4_unrelated_failure"()`); } });
  await test("normal scheduled start and end retain confirmed historical reservation", async () => { const value = await accepted(await fixture(await setup())); await startTrip(db, value.teleporter.id, Role.OPERATOR, value.trip.id, value.reservation.startAt); await endTrip(db, value.teleporter.id, Role.OPERATOR, value.trip.id, value.reservation.endAt); const final = await state(value); assert.equal(final.trip.status, TripStatus.ENDED); assert.equal(final.reservation.status, ScheduledJourneyReservationStatus.CONFIRMED); assert.equal(final.reservation.releasedAt, null); });
  await test("legacy immediate cancellation remains compatible without reservation", async () => { const base = await setup(); const explorer = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, role: Role.VIEWER } }); const trip = await db.trip.create({ data: { viewerId: explorer.id, operatorId: base.teleporter.id, destination: "Immediate", livekitRoom: `${run}-${randomUUID()}`, status: TripStatus.ACCEPTED, acceptedAt: decisionTime } }); assert.equal((await cancelTrip(db, explorer.id, Role.VIEWER, trip.id, decisionTime)).ok, true); assert.equal(await db.scheduledJourneyReservation.count({ where: { tripId: trip.id } }), 0); });
  await test("Proposal rejection before acceptance creates no reservation", async () => { const value = await fixture(await setup()); await db.proposal.update({ where: { id: value.proposal.id }, data: { status: ProposalStatus.DECLINED, terminalAt: decisionTime } }); assert.equal(await db.scheduledJourneyReservation.count({ where: { agreement: { journeyRequestId: value.request.id } } }), 0); });
  await test("future stale recovery scan does not release a still-eligible reservation", async () => { const value = await accepted(await fixture(await setup(), at(120))); await recoverStaleTrips(db, new Date(decisionTime.getTime() + 16 * 60_000)); assert.equal((await state(value)).reservation.status, ScheduledJourneyReservationStatus.CONFIRMED); });
  await test("qualifying stale accepted recovery cancellation releases reservation", async () => { const value = await accepted(await fixture(await setup(), at(120))); await db.trip.update({ where: { id: value.trip.id }, data: { acceptedAt: new Date(0) } }); await recoverStaleTrips(db, new Date(at(120).getTime() + 16 * 60_000)); const final = await state(value); assert.equal(final.trip.status, TripStatus.CANCELLED); assert.equal(final.reservation.status, ScheduledJourneyReservationStatus.RELEASED); });
  await test("unrelated actors cannot cancel or release", async () => { const value = await accepted(await fixture(await setup())); const viewer = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, role: Role.VIEWER } }); const teleporter = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, role: Role.OPERATOR } }); for (const actor of [[viewer.id, Role.VIEWER], [teleporter.id, Role.OPERATOR]] as const) assert.equal((await cancelTrip(db, actor[0], actor[1], value.trip.id, decisionTime)).ok, false); const final = await state(value); assert.equal(final.trip.status, TripStatus.ACCEPTED); assert.equal(final.reservation.status, ScheduledJourneyReservationStatus.CONFIRMED); });
  await test("concurrent duplicate cancellations produce one stable release", async () => { const value = await accepted(await fixture(await setup())); await Promise.allSettled([cancelTrip(db, value.explorer.id, Role.VIEWER, value.trip.id, decisionTime), cancelTrip(db, value.explorer.id, Role.VIEWER, value.trip.id, at(500))]); const final = await state(value); assert.equal(final.trip.status, TripStatus.CANCELLED); assert.equal(final.reservation.status, ScheduledJourneyReservationStatus.RELEASED); assert.ok([decisionTime.getTime(), at(500).getTime()].includes(final.reservation.releasedAt!.getTime())); });
  await test("scheduled start racing cancellation has one coherent winner", async () => { const value = await accepted(await fixture(await setup())); await Promise.allSettled([startTrip(db, value.teleporter.id, Role.OPERATOR, value.trip.id, value.reservation.startAt), cancelTrip(db, value.explorer.id, Role.VIEWER, value.trip.id, value.reservation.startAt)]); const final = await state(value); const started = final.trip.status === TripStatus.IN_PROGRESS && final.reservation.status === ScheduledJourneyReservationStatus.CONFIRMED; const cancelled = final.trip.status === TripStatus.CANCELLED && final.reservation.status === ScheduledJourneyReservationStatus.RELEASED; assert.equal(started || cancelled, true); });
  await test("acceptance cannot use interval before release commits and succeeds after release", async () => { const base = await setup(); const existing = await accepted(await fixture(base)); const replacement = await fixture(base); const raced = await Promise.allSettled([cancelTrip(db, existing.explorer.id, Role.VIEWER, existing.trip.id, decisionTime), acceptProposal(db, replacement.explorer.id, replacement.request.id, replacement.proposal.id, {}, decisionTime)]); void raced; const released = (await state(existing)).reservation.status === ScheduledJourneyReservationStatus.RELEASED; assert.equal(released, true); if (await db.agreement.count({ where: { journeyRequestId: replacement.request.id } }) === 0) assert.equal((await acceptProposal(db, replacement.explorer.id, replacement.request.id, replacement.proposal.id, {}, decisionTime)).ok, true); assert.equal(await db.scheduledJourneyReservation.count({ where: { teleporterId: base.teleporter.id, status: ScheduledJourneyReservationStatus.CONFIRMED } }), 1); });
  await test("cancelling one Trip cannot release or clear another", async () => { const base = await setup(); const first = await accepted(await fixture(base, at(120))); const second = await accepted(await fixture(base, at(240))); await db.user.update({ where: { id: base.teleporter.id }, data: { activeTripId: second.trip.id } }); await cancelTrip(db, first.explorer.id, Role.VIEWER, first.trip.id, decisionTime); assert.equal((await state(first)).reservation.status, ScheduledJourneyReservationStatus.RELEASED); assert.equal((await state(second)).reservation.status, ScheduledJourneyReservationStatus.CONFIRMED); assert.equal((await db.user.findUniqueOrThrow({ where: { id: base.teleporter.id } })).activeTripId, second.trip.id); });
}

main().catch(error => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; }).finally(() => db.$disconnect());
