import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { OperatorPilotStatus, PrismaClient, ProposalStatus, Role, TripStatus } from "@prisma/client";
import { acceptProposal } from "../lib/agreements";
import { endTrip, startTrip } from "../lib/trip-lifecycle";

if (!process.env.PHASE3_TEST_DATABASE_URL || !process.env.PHASE4_TEST_DATABASE_URL || process.env.PHASE3_TEST_DATABASE_URL !== process.env.PHASE4_TEST_DATABASE_URL || process.env.DATABASE_URL !== process.env.PHASE3_TEST_DATABASE_URL) throw new Error("Unsafe database mapping");
const db = new PrismaClient();
const run = `p5a3-${randomUUID()}`;
const decisionTime = new Date("2026-08-01T12:00:00.000Z");
const scheduleOrigin = new Date("2026-09-01T12:00:00.000Z");
const at = (minutes: number) => new Date(scheduleOrigin.getTime() + minutes * 60_000);
async function test(name: string, work: () => Promise<void>) { await work(); console.log(`PASS ${name}`); }

async function setup() {
  const destination = await db.destination.create({ data: { slug: `${run}-${randomUUID()}`, name: "Multiple obligations", shortDescription: "Disposable", city: "Test City", meetingArea: "Gate", category: "Test", durationOptions: [30], active: true } });
  const teleporter = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, name: "Operational Teleporter", role: Role.OPERATOR, operatorProfile: { create: { operatingArea: "Test City", serviceRadiusKm: 10, languages: ["English"], accessibilityCapabilities: [], durationOptions: [30], pilotStatus: OperatorPilotStatus.APPROVED } }, destinationServices: { create: { destinationId: destination.id } } } });
  return { destination, teleporter };
}
async function proposalFixture(base: Awaited<ReturnType<typeof setup>>, start: Date, duration = 30, windowMinutes: number | null = null) {
  const explorer = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, role: Role.VIEWER } });
  const request = await db.journeyRequest.create({ data: { explorerId: explorer.id, destinationId: base.destination.id, publicPlaceName: "Multiple obligations", coarseLocation: "Test City", earliestStart: start, latestStart: new Date(start.getTime() + (windowMinutes ?? 60) * 60_000), durationMinutes: duration, proposedPriceMinor: 2500, currency: "USD", expiresAt: new Date(start.getTime() - 60_000) } });
  const proposal = await db.proposal.create({ data: { journeyRequestId: request.id, teleporterId: base.teleporter.id, version: 1, earliestStart: start, latestStart: windowMinutes === null ? null : new Date(start.getTime() + windowMinutes * 60_000), durationMinutes: duration, proposedPriceMinor: 2500, currency: "USD", validUntil: new Date(start.getTime() - 30_000) } });
  return { ...base, explorer, request, proposal, start, duration };
}
async function accept(f: Awaited<ReturnType<typeof proposalFixture>>, selected = f.start) {
  return acceptProposal(db, f.explorer.id, f.request.id, f.proposal.id, f.proposal.latestStart ? { scheduledStartAt: selected.toISOString() } : {}, decisionTime);
}
async function accepted(f: Awaited<ReturnType<typeof proposalFixture>>, selected = f.start) {
  const result = await accept(f, selected); assert.equal(result.ok, true); if (!result.ok) throw new Error("Acceptance failed");
  const trip = await db.trip.findUniqueOrThrow({ where: { id: result.value.tripId } });
  const reservation = await db.scheduledJourneyReservation.findFirstOrThrow({ where: { agreementId: result.value.id, status: "CONFIRMED" } });
  return { result, trip, reservation };
}
async function noPartial(requestId: string) {
  assert.equal(await db.agreement.count({ where: { journeyRequestId: requestId } }), 0);
  assert.equal(await db.trip.count({ where: { journeyRequest: { is: { id: requestId } } } }), 0);
  assert.equal(await db.scheduledJourneyReservation.count({ where: { agreement: { journeyRequestId: requestId } } }), 0);
  const request = await db.journeyRequest.findUniqueOrThrow({ where: { id: requestId }, include: { proposals: true } });
  assert.equal(request.status, "OPEN"); assert.equal(request.tripId, null); assert.ok(request.proposals.every(item => item.status === ProposalStatus.ACTIVE));
}

async function main() {
  await test("multiple earlier later and adjacent scheduled obligations commit", async () => { const base = await setup(); const fixtures = [await proposalFixture(base, at(120)), await proposalFixture(base, at(240)), await proposalFixture(base, at(60)), await proposalFixture(base, at(270))]; for (const fixture of fixtures) assert.equal((await accept(fixture)).ok, true); assert.equal(await db.agreement.count({ where: { teleporterId: base.teleporter.id } }), 4); assert.equal(await db.trip.count({ where: { operatorId: base.teleporter.id, immediate: false } }), 4); assert.equal(await db.scheduledJourneyReservation.count({ where: { teleporterId: base.teleporter.id } }), 4); assert.equal((await db.user.findUniqueOrThrow({ where: { id: base.teleporter.id } })).activeTripId, null); });
  for (const [name, firstStart, firstDuration, secondStart, secondDuration] of [["partial overlap",0,60,30,60],["contained overlap",0,60,15,15],["containing overlap",15,15,0,60],["identical overlap",0,30,0,30]] as const) await test(`${name} is rejected without partial state`, async () => { const base = await setup(); assert.equal((await accept(await proposalFixture(base, at(firstStart), firstDuration))).ok, true); const loser = await proposalFixture(base, at(secondStart), secondDuration); const result = await accept(loser); assert.equal(result.ok, false); if (!result.ok) { assert.equal(result.status, 409); assert.equal(result.error, "The Teleporter is no longer available for the selected Journey time."); } await noPartial(loser.request.id); });
  await test("scheduled acceptance leaves null activeTripId unchanged", async () => { const base = await setup(); await accepted(await proposalFixture(base, at(120))); assert.equal((await db.user.findUniqueOrThrow({ where: { id: base.teleporter.id } })).activeTripId, null); });
  await test("scheduled acceptance leaves another operational activeTripId unchanged", async () => { const base = await setup(); const viewer = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, role: Role.VIEWER } }); const active = await db.trip.create({ data: { viewerId: viewer.id, operatorId: base.teleporter.id, destination: "Immediate", livekitRoom: `${run}-${randomUUID()}`, status: TripStatus.IN_PROGRESS, acceptedAt: decisionTime, startedAt: decisionTime } }); await db.user.update({ where: { id: base.teleporter.id }, data: { activeTripId: active.id } }); assert.equal((await accept(await proposalFixture(base, at(300)))).ok, true); assert.equal((await db.user.findUniqueOrThrow({ where: { id: base.teleporter.id } })).activeTripId, active.id); });
  await test("same-Proposal retry preserves one Agreement Trip and reservation", async () => { const f = await proposalFixture(await setup(), at(120), 30, 30); const first = await accept(f, at(125)); const retry = await accept(f, at(135)); assert.equal(first.ok, true); assert.equal(retry.ok, true); assert.equal(retry.created, false); assert.equal(await db.agreement.count({ where: { journeyRequestId: f.request.id } }), 1); assert.equal(await db.trip.count({ where: { journeyRequest: { is: { id: f.request.id } } } }), 1); const rows = await db.scheduledJourneyReservation.findMany({ where: { agreement: { journeyRequestId: f.request.id } } }); assert.equal(rows.length, 1); assert.equal(rows[0].startAt.getTime(), at(125).getTime()); });
  await test("different-Proposal retry remains conflict", async () => { const f = await proposalFixture(await setup(), at(120)); const secondOperator = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, role: Role.OPERATOR } }); const other = await db.proposal.create({ data: { journeyRequestId: f.request.id, teleporterId: secondOperator.id, version: 1, earliestStart: at(180), durationMinutes: 30, proposedPriceMinor: 2500, currency: "USD", validUntil: at(100) } }); assert.equal((await accept(f)).ok, true); const retry = await acceptProposal(db, f.explorer.id, f.request.id, other.id, {}, decisionTime); assert.equal(retry.ok, false); if (!retry.ok) assert.equal(retry.status, 409); });
  await test("forced failure rolls back all acceptance mutations", async () => { const f = await proposalFixture(await setup(), at(120)); await db.$executeRawUnsafe(`CREATE OR REPLACE FUNCTION "phase5a3_force_failure"() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'forced'; END; $$ LANGUAGE plpgsql`); await db.$executeRawUnsafe(`CREATE TRIGGER "phase5a3_force_failure" BEFORE UPDATE ON "JourneyRequest" FOR EACH ROW WHEN (NEW."status" = 'CONVERTED') EXECUTE FUNCTION "phase5a3_force_failure"()`); try { await assert.rejects(accept(f)); await noPartial(f.request.id); assert.equal((await db.user.findUniqueOrThrow({ where: { id: f.teleporter.id } })).activeTripId, null); } finally { await db.$executeRawUnsafe(`DROP TRIGGER IF EXISTS "phase5a3_force_failure" ON "JourneyRequest"`); await db.$executeRawUnsafe(`DROP FUNCTION IF EXISTS "phase5a3_force_failure"()`); } });

  await test("scheduled start claims activeTripId exactly at startAt", async () => { const f = await proposalFixture(await setup(), at(120)); const { trip, reservation } = await accepted(f); const result = await startTrip(db, f.teleporter.id, Role.OPERATOR, trip.id, reservation.startAt); assert.equal(result.ok, true); assert.equal((await db.trip.findUniqueOrThrow({ where: { id: trip.id } })).status, TripStatus.IN_PROGRESS); assert.equal((await db.user.findUniqueOrThrow({ where: { id: f.teleporter.id } })).activeTripId, trip.id); });
  await test("early scheduled start fails without activation", async () => { const f = await proposalFixture(await setup(), at(120)); const { trip, reservation } = await accepted(f); const result = await startTrip(db, f.teleporter.id, Role.OPERATOR, trip.id, new Date(reservation.startAt.getTime() - 1)); assert.equal(result.ok, false); if (!result.ok) assert.equal(result.error, "Confirmed Journey has not reached its agreed start time"); assert.equal((await db.trip.findUniqueOrThrow({ where: { id: trip.id } })).status, TripStatus.ACCEPTED); assert.equal((await db.user.findUniqueOrThrow({ where: { id: f.teleporter.id } })).activeTripId, null); });
  await test("late start and same-Trip retry are allowed", async () => { const f = await proposalFixture(await setup(), at(120)); const { trip, reservation } = await accepted(f); assert.equal((await startTrip(db, f.teleporter.id, Role.OPERATOR, trip.id, new Date(reservation.startAt.getTime() + 60_000))).ok, true); assert.equal((await startTrip(db, f.teleporter.id, Role.OPERATOR, trip.id, new Date(reservation.startAt.getTime() + 120_000))).ok, true); assert.equal((await db.user.findUniqueOrThrow({ where: { id: f.teleporter.id } })).activeTripId, trip.id); });
  await test("different active Journey produces stable operational conflict", async () => { const base = await setup(); const first = await accepted(await proposalFixture(base, at(120))); const second = await accepted(await proposalFixture(base, at(240))); assert.equal((await startTrip(db, base.teleporter.id, Role.OPERATOR, first.trip.id, first.reservation.startAt)).ok, true); const result = await startTrip(db, base.teleporter.id, Role.OPERATOR, second.trip.id, second.reservation.startAt); assert.equal(result.ok, false); if (!result.ok) assert.equal(result.error, "Another Journey is currently active. End it before starting this Journey."); assert.equal((await db.trip.findUniqueOrThrow({ where: { id: second.trip.id } })).status, TripStatus.ACCEPTED); assert.equal((await db.user.findUniqueOrThrow({ where: { id: base.teleporter.id } })).activeTripId, first.trip.id); });
  await test("end clears only owning activeTripId and later Trip can start", async () => { const base = await setup(); const first = await accepted(await proposalFixture(base, at(120))); const second = await accepted(await proposalFixture(base, at(240))); await startTrip(db, base.teleporter.id, Role.OPERATOR, first.trip.id, first.reservation.startAt); assert.equal((await endTrip(db, base.teleporter.id, Role.OPERATOR, first.trip.id, first.reservation.endAt)).ok, true); assert.equal((await db.user.findUniqueOrThrow({ where: { id: base.teleporter.id } })).activeTripId, null); assert.equal((await startTrip(db, base.teleporter.id, Role.OPERATOR, second.trip.id, second.reservation.startAt)).ok, true); });
  await test("ending non-owner Trip cannot clear another active claim", async () => { const base = await setup(); const first = await accepted(await proposalFixture(base, at(120))); const second = await accepted(await proposalFixture(base, at(240))); await db.trip.update({ where: { id: first.trip.id }, data: { status: TripStatus.IN_PROGRESS, startedAt: first.reservation.startAt } }); await db.user.update({ where: { id: base.teleporter.id }, data: { activeTripId: second.trip.id } }); assert.equal((await endTrip(db, base.teleporter.id, Role.OPERATOR, first.trip.id, first.reservation.endAt)).ok, true); assert.equal((await db.user.findUniqueOrThrow({ where: { id: base.teleporter.id } })).activeTripId, second.trip.id); });
  await test("Viewer and unrelated Teleporter cannot activate", async () => { const f = await proposalFixture(await setup(), at(120)); const { trip, reservation } = await accepted(f); const stranger = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, role: Role.OPERATOR } }); for (const actor of [[f.explorer.id,Role.VIEWER],[stranger.id,Role.OPERATOR]] as const) { const result = await startTrip(db, actor[0], actor[1], trip.id, reservation.startAt); assert.equal(result.ok, false); if (!result.ok) assert.equal(result.status, 404); } assert.equal((await db.trip.findUniqueOrThrow({ where: { id: trip.id } })).status, TripStatus.ACCEPTED); });
  await test("legacy immediate Trip start remains compatible", async () => { const base = await setup(); const viewer = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, role: Role.VIEWER } }); const trip = await db.trip.create({ data: { viewerId: viewer.id, operatorId: base.teleporter.id, destination: "Immediate", livekitRoom: `${run}-${randomUUID()}`, status: TripStatus.ACCEPTED, acceptedAt: decisionTime } }); await db.user.update({ where: { id: base.teleporter.id }, data: { activeTripId: trip.id } }); assert.equal((await startTrip(db, base.teleporter.id, Role.OPERATOR, trip.id, decisionTime)).ok, true); });

  await test("concurrent non-overlapping scheduled acceptances both commit", async () => { const base = await setup(); const first = await proposalFixture(base, at(500)), second = await proposalFixture(base, at(600)); const results = await Promise.all([accept(first), accept(second)]); assert.ok(results.every(result => result.ok)); assert.equal(await db.scheduledJourneyReservation.count({ where: { teleporterId: base.teleporter.id } }), 2); });
  await test("concurrent overlapping acceptances commit one complete winner", async () => { const base = await setup(); const first = await proposalFixture(base, at(700), 60), second = await proposalFixture(base, at(730), 60); await Promise.allSettled([accept(first), accept(second)]); const agreements = await db.agreement.count({ where: { teleporterId: base.teleporter.id } }); const trips = await db.trip.count({ where: { operatorId: base.teleporter.id, immediate: false } }); const reservations = await db.scheduledJourneyReservation.count({ where: { teleporterId: base.teleporter.id } }); assert.deepEqual([agreements,trips,reservations],[1,1,1]); });
  await test("concurrent starts produce exactly one active Trip", async () => { const base = await setup(); const first = await accepted(await proposalFixture(base, at(800))), second = await accepted(await proposalFixture(base, at(900))); await Promise.allSettled([startTrip(db, base.teleporter.id, Role.OPERATOR, first.trip.id, at(1000)), startTrip(db, base.teleporter.id, Role.OPERATOR, second.trip.id, at(1000))]); const trips = await db.trip.findMany({ where: { id: { in: [first.trip.id, second.trip.id] } } }); assert.equal(trips.filter(trip => trip.status === TripStatus.IN_PROGRESS).length, 1); const active = (await db.user.findUniqueOrThrow({ where: { id: base.teleporter.id } })).activeTripId; assert.equal(trips.some(trip => trip.id === active && trip.status === TripStatus.IN_PROGRESS), true); });
  await test("concurrent same-Trip start remains consistent", async () => { const f = await proposalFixture(await setup(), at(1100)); const value = await accepted(f); await Promise.allSettled([startTrip(db, f.teleporter.id, Role.OPERATOR, value.trip.id, value.reservation.startAt), startTrip(db, f.teleporter.id, Role.OPERATOR, value.trip.id, value.reservation.startAt)]); assert.equal((await db.trip.findUniqueOrThrow({ where: { id: value.trip.id } })).status, TripStatus.IN_PROGRESS); assert.equal((await db.user.findUniqueOrThrow({ where: { id: f.teleporter.id } })).activeTripId, value.trip.id); });
}

main().catch(error => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; }).finally(() => db.$disconnect());
