import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { AgreementStatus, OperatorPilotStatus, Prisma, PrismaClient, ProposalStatus, Role, ScheduledJourneyReservationStatus, TripStatus } from "@prisma/client";
import { acceptProposal, getExplorerAgreement } from "../lib/agreements";

if (!process.env.PHASE3_TEST_DATABASE_URL || !process.env.PHASE4_TEST_DATABASE_URL || process.env.PHASE3_TEST_DATABASE_URL !== process.env.PHASE4_TEST_DATABASE_URL || process.env.DATABASE_URL !== process.env.PHASE3_TEST_DATABASE_URL) throw new Error("Unsafe database mapping");
const db = new PrismaClient();
const run = `p5a2-${randomUUID()}`;
const origin = new Date("2026-09-01T12:00:00.000Z");
const at = (minutes: number) => new Date(origin.getTime() + minutes * 60_000);
async function test(name: string, work: () => Promise<void>) { await work(); console.log(`PASS ${name}`); }

async function operator(destinationId?: string) {
  return db.user.create({ data: { clerkId: `${run}-operator-${randomUUID()}`, name: "Reservation Teleporter", role: Role.OPERATOR, operatorProfile: destinationId ? { create: { operatingArea: "Test City", serviceRadiusKm: 10, languages: ["English"], accessibilityCapabilities: [], durationOptions: [30, 45], pilotStatus: OperatorPilotStatus.APPROVED } } : undefined, destinationServices: destinationId ? { create: { destinationId } } : undefined } });
}
async function directContract(teleporterId: string, startAt: Date, durationMinutes = 30) {
  const explorer = await db.user.create({ data: { clerkId: `${run}-explorer-${randomUUID()}`, role: Role.VIEWER } });
  const request = await db.journeyRequest.create({ data: { explorerId: explorer.id, publicPlaceName: "Direct constraint fixture", coarseLocation: "Test City", earliestStart: startAt, latestStart: new Date(startAt.getTime() + 60_000), durationMinutes, proposedPriceMinor: 1000, currency: "USD", expiresAt: new Date(startAt.getTime() - 60_000) } });
  const proposal = await db.proposal.create({ data: { journeyRequestId: request.id, teleporterId, version: 1, earliestStart: startAt, durationMinutes, proposedPriceMinor: 1000, currency: "USD", validUntil: new Date(startAt.getTime() - 30_000), status: ProposalStatus.ACCEPTED, terminalAt: origin } });
  const trip = await db.trip.create({ data: { viewerId: explorer.id, operatorId: teleporterId, destination: "Direct fixture", livekitRoom: `${run}-${randomUUID()}`, immediate: false, requestedDuration: durationMinutes, status: TripStatus.ENDED, requestedAt: origin, acceptedAt: origin, startedAt: origin, endedAt: origin } });
  const agreement = await db.agreement.create({ data: { journeyRequestId: request.id, proposalId: proposal.id, explorerId: explorer.id, teleporterId, tripId: trip.id, agreedStartAt: startAt, agreedEarliestStart: startAt, agreedDurationMinutes: durationMinutes, agreedPriceMinor: 1000, currency: "USD", publicPlaceNameSnapshot: "Direct constraint fixture", coarseLocationSnapshot: "Test City", status: AgreementStatus.CONFIRMED, confirmedAt: origin } });
  await db.journeyRequest.update({ where: { id: request.id }, data: { status: "CONVERTED", convertedAt: origin, tripId: trip.id } });
  return { explorer, request, proposal, trip, agreement, teleporterId, startAt, endAt: new Date(startAt.getTime() + durationMinutes * 60_000) };
}
async function insertReservation(contract: Awaited<ReturnType<typeof directContract>>, status: ScheduledJourneyReservationStatus = ScheduledJourneyReservationStatus.CONFIRMED, releasedAt: Date | null = null) {
  return db.scheduledJourneyReservation.create({ data: { teleporterId: contract.teleporterId, agreementId: contract.agreement.id, tripId: contract.trip.id, startAt: contract.startAt, endAt: contract.endAt, status, releasedAt } });
}
async function overlapCase(name: string, baseStart: number, baseDuration: number, candidateStart: number, candidateDuration: number, conflicts: boolean) {
  await test(name, async () => { const teleporter = await operator(); const base = await directContract(teleporter.id, at(baseStart), baseDuration); await insertReservation(base); const candidate = await directContract(teleporter.id, at(candidateStart), candidateDuration); if (conflicts) await assert.rejects(insertReservation(candidate)); else await insertReservation(candidate); });
}
async function acceptanceFixture(windowed: boolean, existingOperator?: Awaited<ReturnType<typeof operator>>, operatorCount = 1) {
  const destination = await db.destination.create({ data: { slug: `${run}-${randomUUID()}`, name: "Scheduled acceptance", shortDescription: "Disposable", city: "Test City", meetingArea: "Gate", category: "Test", durationOptions: [30, 45], active: true } });
  const explorer = await db.user.create({ data: { clerkId: `${run}-${randomUUID()}`, role: Role.VIEWER } });
  const operators = [];
  if (existingOperator) { await db.operatorProfile.upsert({ where: { userId: existingOperator.id }, create: { userId: existingOperator.id, operatingArea: "Test City", serviceRadiusKm: 10, languages: ["English"], accessibilityCapabilities: [], durationOptions: [30, 45], pilotStatus: OperatorPilotStatus.APPROVED }, update: {} }); await db.operatorDestination.create({ data: { operatorId: existingOperator.id, destinationId: destination.id } }); operators.push(existingOperator); }
  while (operators.length < operatorCount) operators.push(await operator(destination.id));
  const request = await db.journeyRequest.create({ data: { explorerId: explorer.id, destinationId: destination.id, publicPlaceName: "Scheduled acceptance", coarseLocation: "Test City", earliestStart: at(120), latestStart: at(180), durationMinutes: 45, proposedPriceMinor: 2500, currency: "USD", expiresAt: at(90) } });
  const proposals = [];
  for (const [index, teleporter] of operators.entries()) proposals.push(await db.proposal.create({ data: { journeyRequestId: request.id, teleporterId: teleporter.id, version: 1, earliestStart: at(120 + index), latestStart: windowed ? at(150 + index) : null, durationMinutes: 45, proposedPriceMinor: 2500, currency: "USD", validUntil: at(60) } }));
  return { destination, explorer, operators, request, proposals };
}
async function unchanged(requestId: string, teleporterId: string) {
  assert.equal(await db.agreement.count({ where: { journeyRequestId: requestId } }), 0);
  assert.equal(await db.trip.count({ where: { journeyRequest: { is: { id: requestId } } } }), 0);
  assert.equal(await db.scheduledJourneyReservation.count({ where: { agreement: { journeyRequestId: requestId } } }), 0);
  const request = await db.journeyRequest.findUniqueOrThrow({ where: { id: requestId }, include: { proposals: true } });
  assert.equal(request.status, "OPEN"); assert.equal(request.tripId, null); assert.ok(request.proposals.every(value => value.status === ProposalStatus.ACTIVE));
  assert.equal((await db.user.findUniqueOrThrow({ where: { id: teleporterId } })).activeTripId, null);
}

async function main() {
  await test("first CONFIRMED reservation succeeds", async () => { const op = await operator(); await insertReservation(await directContract(op.id, at(0))); });
  await overlapCase("non-overlapping earlier reservation succeeds", 60, 30, 0, 30, false);
  await overlapCase("non-overlapping later reservation succeeds", 0, 30, 60, 30, false);
  await overlapCase("partially overlapping reservation conflicts", 0, 60, 30, 60, true);
  await overlapCase("contained reservation conflicts", 0, 60, 15, 15, true);
  await overlapCase("containing reservation conflicts", 15, 15, 0, 60, true);
  await overlapCase("identical interval conflicts", 0, 30, 0, 30, true);
  await overlapCase("same start with different end conflicts", 0, 30, 0, 60, true);
  await overlapCase("same end with different start conflicts", 0, 60, 30, 30, true);
  await overlapCase("adjacent interval before succeeds", 30, 30, 0, 30, false);
  await overlapCase("adjacent interval after succeeds", 0, 30, 30, 30, false);
  await test("same interval for different Teleporter succeeds", async () => { for (let i = 0; i < 2; i++) { const op = await operator(); await insertReservation(await directContract(op.id, at(0))); } });
  await test("RELEASED reservation does not block CONFIRMED", async () => { const op = await operator(); await insertReservation(await directContract(op.id, at(0)), ScheduledJourneyReservationStatus.RELEASED, origin); await insertReservation(await directContract(op.id, at(0))); });
  await test("invalid zero and negative intervals are rejected", async () => { const op = await operator(); for (const end of [at(0), at(-1)]) { const c = await directContract(op.id, at(0)); await assert.rejects(db.scheduledJourneyReservation.create({ data: { teleporterId: op.id, agreementId: c.agreement.id, tripId: c.trip.id, startAt: at(0), endAt: end } })); } });
  await test("invalid state and releasedAt combinations are rejected", async () => { const op = await operator(); const confirmed = await directContract(op.id, at(0)); await assert.rejects(insertReservation(confirmed, ScheduledJourneyReservationStatus.CONFIRMED, origin)); const released = await directContract(op.id, at(60)); await assert.rejects(insertReservation(released, ScheduledJourneyReservationStatus.RELEASED, null)); });
  await test("duplicate agreementId and tripId are rejected", async () => { const op = await operator(); const c = await directContract(op.id, at(0)); await insertReservation(c); await assert.rejects(db.scheduledJourneyReservation.create({ data: { teleporterId: op.id, agreementId: c.agreement.id, tripId: (await directContract(op.id, at(60))).trip.id, startAt: at(60), endAt: at(90) } })); const other = await directContract(op.id, at(120)); await assert.rejects(db.scheduledJourneyReservation.create({ data: { teleporterId: op.id, agreementId: other.agreement.id, tripId: c.trip.id, startAt: at(120), endAt: at(150) } })); });
  await test("direct SQL bypass remains overlap-protected", async () => { const op = await operator(); const base = await directContract(op.id, at(0)); await insertReservation(base); const c = await directContract(op.id, at(15)); await assert.rejects(db.$executeRaw(Prisma.sql`INSERT INTO "ScheduledJourneyReservation" ("id","teleporterId","agreementId","tripId","startAt","endAt","status") VALUES (${randomUUID()}::uuid,${op.id},${c.agreement.id},${c.trip.id},${c.startAt},${c.endAt},'CONFIRMED')`)); });

  await test("fixed acceptance creates exact duration reservation and preserves activeTripId", async () => { const f = await acceptanceFixture(false); const result = await acceptProposal(db, f.explorer.id, f.request.id, f.proposals[0].id, {}, origin); assert.equal(result.ok, true); if (!result.ok) return; const reservation = await db.scheduledJourneyReservation.findUniqueOrThrow({ where: { agreementId: result.value.id } }); assert.equal(reservation.startAt.getTime(), f.proposals[0].earliestStart.getTime()); assert.equal(reservation.endAt.getTime(), reservation.startAt.getTime() + f.proposals[0].durationMinutes * 60_000); assert.equal((await db.user.findUniqueOrThrow({ where: { id: f.operators[0].id } })).activeTripId, result.value.tripId); });
  await test("windowed acceptance reserves selected exact interval without window or buffer", async () => { const f = await acceptanceFixture(true); const selected = at(135); const result = await acceptProposal(db, f.explorer.id, f.request.id, f.proposals[0].id, { scheduledStartAt: selected.toISOString() }, origin); assert.equal(result.ok, true); if (!result.ok) return; const reservation = await db.scheduledJourneyReservation.findUniqueOrThrow({ where: { agreementId: result.value.id } }); assert.equal(reservation.startAt.getTime(), selected.getTime()); assert.equal(reservation.endAt.getTime(), selected.getTime() + 45 * 60_000); assert.notEqual(reservation.endAt.getTime(), f.proposals[0].latestStart!.getTime()); });
  await test("same-Proposal retry preserves one immutable reservation", async () => { const f = await acceptanceFixture(true); const first = at(125), second = at(145); const accepted = await acceptProposal(db, f.explorer.id, f.request.id, f.proposals[0].id, { scheduledStartAt: first.toISOString() }, origin); assert.equal(accepted.ok, true); const retry = await acceptProposal(db, f.explorer.id, f.request.id, f.proposals[0].id, { scheduledStartAt: second.toISOString() }, origin); assert.equal(retry.ok, true); assert.equal(retry.created, false); const rows = await db.scheduledJourneyReservation.findMany({ where: { agreement: { journeyRequestId: f.request.id } } }); assert.equal(rows.length, 1); assert.equal(rows[0].startAt.getTime(), first.getTime()); });
  await test("different-Proposal retry remains conflict", async () => { const f = await acceptanceFixture(true, undefined, 2); assert.equal((await acceptProposal(db, f.explorer.id, f.request.id, f.proposals[0].id, { scheduledStartAt: at(125).toISOString() }, origin)).ok, true); const retry = await acceptProposal(db, f.explorer.id, f.request.id, f.proposals[1].id, { scheduledStartAt: at(130).toISOString() }, origin); assert.equal(retry.ok, false); if (!retry.ok) assert.equal(retry.status, 409); });
  await test("forced post-reservation failure rolls back all acceptance state", async () => { const f = await acceptanceFixture(false); await db.$executeRawUnsafe(`CREATE OR REPLACE FUNCTION "phase5a2_force_conversion_failure"() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'forced rollback'; END; $$ LANGUAGE plpgsql`); await db.$executeRawUnsafe(`CREATE TRIGGER "phase5a2_force_conversion_failure" BEFORE UPDATE ON "JourneyRequest" FOR EACH ROW WHEN (NEW."status" = 'CONVERTED') EXECUTE FUNCTION "phase5a2_force_conversion_failure"()`); try { await assert.rejects(acceptProposal(db, f.explorer.id, f.request.id, f.proposals[0].id, {}, origin)); await unchanged(f.request.id, f.operators[0].id); } finally { await db.$executeRawUnsafe(`DROP TRIGGER IF EXISTS "phase5a2_force_conversion_failure" ON "JourneyRequest"`); await db.$executeRawUnsafe(`DROP FUNCTION IF EXISTS "phase5a2_force_conversion_failure"()`); } });
  await test("exclusion conflict maps to stable 409 with no partial state", async () => { const op = await operator(); const f = await acceptanceFixture(false, op); await insertReservation(await directContract(op.id, f.proposals[0].earliestStart, 45)); const result = await acceptProposal(db, f.explorer.id, f.request.id, f.proposals[0].id, {}, origin); assert.equal(result.ok, false); if (!result.ok) { assert.equal(result.status, 409); assert.equal(result.error, "The Teleporter is no longer available for the selected Journey time."); } await unchanged(f.request.id, op.id); });
  await test("unrelated database failure is not mislabeled", async () => { const f = await acceptanceFixture(false); await db.$executeRawUnsafe(`CREATE OR REPLACE FUNCTION "phase5a2_unrelated_failure"() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'unrelated failure'; END; $$ LANGUAGE plpgsql`); await db.$executeRawUnsafe(`CREATE TRIGGER "phase5a2_unrelated_failure" BEFORE INSERT ON "Agreement" FOR EACH ROW EXECUTE FUNCTION "phase5a2_unrelated_failure"()`); try { await assert.rejects(acceptProposal(db, f.explorer.id, f.request.id, f.proposals[0].id, {} ,origin)); await unchanged(f.request.id, f.operators[0].id); } finally { await db.$executeRawUnsafe(`DROP TRIGGER IF EXISTS "phase5a2_unrelated_failure" ON "Agreement"`); await db.$executeRawUnsafe(`DROP FUNCTION IF EXISTS "phase5a2_unrelated_failure"()`); } });
  await test("legacy Agreement without reservation remains readable", async () => { const op = await operator(); const legacy = await directContract(op.id, at(500)); assert.equal(await db.scheduledJourneyReservation.count({ where: { agreementId: legacy.agreement.id } }), 0); assert.equal((await getExplorerAgreement(db, legacy.explorer.id, legacy.request.id))?.id, legacy.agreement.id); });

  await test("concurrent overlapping direct inserts commit exactly one", async () => { const op = await operator(); const a = await directContract(op.id, at(600)), b = await directContract(op.id, at(615)); const results = await Promise.allSettled([insertReservation(a), insertReservation(b)]); assert.equal(results.filter(value => value.status === "fulfilled").length, 1); assert.equal(await db.scheduledJourneyReservation.count({ where: { agreementId: { in: [a.agreement.id, b.agreement.id] } } }), 1); });
  await test("concurrent non-overlapping direct inserts both commit", async () => { const op = await operator(); const a = await directContract(op.id, at(700)), b = await directContract(op.id, at(730)); const results = await Promise.allSettled([insertReservation(a), insertReservation(b)]); assert.equal(results.filter(value => value.status === "fulfilled").length, 2); assert.equal(await db.scheduledJourneyReservation.count({ where: { agreementId: { in: [a.agreement.id, b.agreement.id] } } }), 2); });
  await test("concurrent application overlap leaves no loser state", async () => { const op = await operator(); const first = await acceptanceFixture(false, op); const second = await acceptanceFixture(false, op); await insertReservation(await directContract(op.id, at(120), 45)); const results = await Promise.all([acceptProposal(db, first.explorer.id, first.request.id, first.proposals[0].id, {}, origin), acceptProposal(db, second.explorer.id, second.request.id, second.proposals[0].id, {}, origin)]); assert.ok(results.every(value => !value.ok && value.status === 409)); await unchanged(first.request.id, op.id); await unchanged(second.request.id, op.id); });
  await test("concurrent same-Proposal retry commits one Agreement Trip and reservation", async () => { const f = await acceptanceFixture(true); const input = { scheduledStartAt: at(130).toISOString() }; await Promise.allSettled([acceptProposal(db, f.explorer.id, f.request.id, f.proposals[0].id, input, origin), acceptProposal(db, f.explorer.id, f.request.id, f.proposals[0].id, input, origin)]); assert.equal(await db.agreement.count({ where: { journeyRequestId: f.request.id } }), 1); assert.equal(await db.trip.count({ where: { journeyRequest: { is: { id: f.request.id } } } }), 1); assert.equal(await db.scheduledJourneyReservation.count({ where: { agreement: { journeyRequestId: f.request.id } } }), 1); });
}

main().catch(error => { console.error(error instanceof Error ? error.message : error); process.exitCode = 1; }).finally(() => db.$disconnect());
