import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { AccountStatus, OperatorPilotStatus, PrismaClient, Role, SafetyReportCategory, SafetyReportRole, SafetyReportSeverity, TripStatus } from "@prisma/client";
import { acquireSafetyRestrictionParticipantLocks, hasEffectiveSafetyRestrictionInTransaction } from "../lib/safety-restriction-lock";
import { approveSafetyRestrictionForAdmin, proposeSafetyRestrictionForAdmin, SafetyRestrictionError } from "../lib/safety-restrictions";
if(process.env.DATABASE_URL!==process.env.PHASE3_TEST_DATABASE_URL||process.env.PHASE3_TEST_DATABASE_URL!==process.env.PHASE4_TEST_DATABASE_URL)throw new Error("Unsafe database mapping");
const db=new PrismaClient(),observer=new PrismaClient(),run=`restriction-race-${randomUUID()}`,raceClients:PrismaClient[]=[];
function raceClient(name:string){const url=new URL(process.env.DATABASE_URL!);url.searchParams.set("application_name",`${run}-${name}`);const client=new PrismaClient({datasources:{db:{url:url.toString()}},transactionOptions:{timeout:30000}});raceClients.push(client);return client}
const deferred=()=>{let resolve!:()=>void;const promise=new Promise<void>(r=>{resolve=r});return{promise,resolve}};
async function holdParticipantLock(client:PrismaClient,participantId:string){const acquired=deferred(),release=deferred();const done=client.$transaction(async tx=>{await acquireSafetyRestrictionParticipantLocks(tx,[participantId]);acquired.resolve();await release.promise});await acquired.promise;return{release:release.resolve,done}}
async function waitForAdvisoryWaiters(participantId:string,count:number){const lockText=`safety-reporting-phase4d:participant:${participantId}`;for(let attempt=0;attempt<10000;attempt++){const rows=await observer.$queryRaw<Array<{count:bigint}>>`SELECT count(*)::bigint AS count FROM pg_locks WHERE locktype='advisory' AND NOT granted AND classid=(((hashtextextended(${lockText},0)>>32)&4294967295)::oid) AND objid=((hashtextextended(${lockText},0)&4294967295)::oid)`;if(Number(rows[0].count)>=count)return;await new Promise<void>(resolve=>setImmediate(resolve))}throw new Error("Participant advisory-lock barrier was not reached")}
async function fixture(suffix:string){const proposer=await db.user.create({data:{clerkId:`${run}-${suffix}-p`,role:Role.ADMIN,accountStatus:AccountStatus.ACTIVE}}),approver=await db.user.create({data:{clerkId:`${run}-${suffix}-a`,role:Role.ADMIN,accountStatus:AccountStatus.ACTIVE}}),viewer=await db.user.create({data:{clerkId:`${run}-${suffix}-v`}}),reported=await db.user.create({data:{clerkId:`${run}-${suffix}-r`,role:Role.OPERATOR}}),operator=await db.user.create({data:{clerkId:`${run}-${suffix}-o`,role:Role.OPERATOR,online:true}}),destination=await db.destination.create({data:{slug:`${run}-${suffix}`,name:"Race destination",shortDescription:"Concurrency fixture",city:"Race City",meetingArea:"Entrance",category:"Test",durationOptions:[30]}});await db.operatorProfile.create({data:{userId:operator.id,operatingArea:"Race City",serviceRadiusKm:25,languages:["English"],accessibilityCapabilities:[],durationOptions:[30],pilotStatus:OperatorPilotStatus.APPROVED}});await db.operatorDestination.create({data:{operatorId:operator.id,destinationId:destination.id}});const historical=await db.trip.create({data:{viewerId:viewer.id,operatorId:reported.id,destination:"Historical safety Journey",livekitRoom:`${run}-${suffix}-history`,status:TripStatus.ENDED,endedAt:new Date()}}),report=await db.safetyReport.create({data:{tripId:historical.id,reporterId:viewer.id,reportedId:reported.id,reporterRole:SafetyReportRole.EXPLORER,reportedRole:SafetyReportRole.TELEPORTER,category:SafetyReportCategory.OTHER,severity:SafetyReportSeverity.LOW,narrative:"Immutable concurrency fixture."}}),proposal=await proposeSafetyRestrictionForAdmin(db,proposer.id,report.id,{participantRole:"REPORTER",duration:"HOURS_24",internalReason:"Concurrency test basis",participantExplanation:"Neutral concurrency test explanation"});return{approver,viewer,destination,proposal}}
const journey=(client:PrismaClient,viewerId:string,destinationId:string)=>client.$transaction(async tx=>{await acquireSafetyRestrictionParticipantLocks(tx,[viewerId]);if(await hasEffectiveSafetyRestrictionInTransaction(tx,[viewerId]))return{ok:false as const};await tx.trip.create({data:{viewerId,destinationId,destination:"Race destination",operatingArea:"Race City",meetingArea:"Entrance",requestedDuration:30,livekitRoom:`${run}-${randomUUID()}`,status:TripStatus.REQUESTED}});return{ok:true as const}},{isolationLevel:"ReadCommitted"});
async function main(){const blockerA=raceClient("blocker-a"),approvalA=raceClient("approval-a"),journeyA=raceClient("journey-a"),a=await fixture("approval-first"),barrierA=await holdParticipantLock(blockerA,a.viewer.id),approval=approveSafetyRestrictionForAdmin(approvalA,a.approver.id,a.proposal.id,{});await waitForAdvisoryWaiters(a.viewer.id,1);const losingJourney=journey(journeyA,a.viewer.id,a.destination.id);await waitForAdvisoryWaiters(a.viewer.id,2);barrierA.release();await barrierA.done;const[approved,journeyResult]=await Promise.all([approval,losingJourney]);assert.equal(approved.status,"ACTIVE");assert.equal(journeyResult.ok,false);assert.equal(await db.safetyReportRestrictionEvent.count({where:{restrictionId:a.proposal.id,eventType:"APPROVED_AND_ACTIVATED"}}),1);assert.equal(await db.trip.count({where:{viewerId:a.viewer.id,status:{in:["REQUESTED","OFFERED","ACCEPTED","IN_PROGRESS"]}}}),0);console.log("PASS approval wins: Journey creation rolls back without a pairing or duplicate activation event");const blockerB=raceClient("blocker-b"),journeyB=raceClient("journey-b"),approvalB=raceClient("approval-b"),b=await fixture("journey-first"),barrierB=await holdParticipantLock(blockerB,b.viewer.id),winningJourney=journey(journeyB,b.viewer.id,b.destination.id);await waitForAdvisoryWaiters(b.viewer.id,1);const losingApproval=approveSafetyRestrictionForAdmin(approvalB,b.approver.id,b.proposal.id,{});await waitForAdvisoryWaiters(b.viewer.id,2);barrierB.release();await barrierB.done;const created=await winningJourney;assert.equal(created.ok,true);await assert.rejects(losingApproval,(error:unknown)=>error instanceof SafetyRestrictionError&&error.code==="ACTIVE_JOURNEY");const unchanged=await db.safetyReportRestriction.findUniqueOrThrow({where:{id:b.proposal.id}});assert.equal(unchanged.status,"PROPOSED");assert.equal(unchanged.approvedByAdministratorId,null);assert.equal(unchanged.startsAt,null);assert.equal(await db.safetyReportRestrictionEvent.count({where:{restrictionId:b.proposal.id,eventType:"APPROVED_AND_ACTIVATED"}}),0);console.log("PASS Journey wins: restriction remains proposed with no activation fields or event")}
main().catch(error=>{console.error(error);process.exitCode=1}).finally(async()=>{await db.$executeRawUnsafe('ALTER TABLE "SafetyReportRestrictionEvent" DISABLE TRIGGER "SafetyReportRestrictionEvent_append_only_delete"');await db.safetyReportRestrictionEvent.deleteMany({where:{restriction:{safetyReport:{trip:{viewer:{clerkId:{startsWith:run}}}}}}});await db.$executeRawUnsafe('ALTER TABLE "SafetyReportRestrictionEvent" ENABLE TRIGGER "SafetyReportRestrictionEvent_append_only_delete"');await db.safetyReportRestriction.deleteMany({where:{safetyReport:{trip:{viewer:{clerkId:{startsWith:run}}}}}});await db.safetyReport.deleteMany({where:{trip:{viewer:{clerkId:{startsWith:run}}}}});await db.tripOffer.deleteMany({where:{trip:{viewer:{clerkId:{startsWith:run}}}}});await db.trip.deleteMany({where:{viewer:{clerkId:{startsWith:run}}}});await db.operatorDestination.deleteMany({where:{operator:{clerkId:{startsWith:run}}}});await db.operatorProfile.deleteMany({where:{user:{clerkId:{startsWith:run}}}});await db.destination.deleteMany({where:{slug:{startsWith:run}}});await db.user.deleteMany({where:{clerkId:{startsWith:run}}});await Promise.all([db.$disconnect(),observer.$disconnect(),...raceClients.map(client=>client.$disconnect())])});
