import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const read = (path) => readFileSync(path, "utf8");
const schema = read("prisma/schema.prisma");
const trips = read("app/api/trips/route.ts");
const offers = read("app/api/operator/offers/route.ts");
const accept = read("app/api/trips/[id]/accept/route.ts");
const decline = read("app/api/operator/offers/[id]/decline/route.ts");
const settings = read("app/api/operator/settings/route.ts");
const online = read("app/api/operator/online/route.ts");
const destinations = read("app/api/destinations/route.ts");
const marketplace = read("lib/marketplace.ts");
const services = read("lib/phase3-services.ts");
const cancel = read("app/api/trips/[id]/cancel/route.ts");
const end = read("app/api/trips/[id]/end/route.ts");
const viewer = read("app/viewer/page.tsx");
const operator = read("app/operator/page.tsx");
const room = read("components/VideoRoom.tsx");

assert.match(schema, /model Destination/);
assert.match(schema, /model OperatorProfile/);
assert.match(schema, /model TripOffer/);
assert.match(schema, /@@unique\(\[tripId, operatorId\]\)/);
assert.match(schema, /pendingOfferTripId\s+String\?/);
assert.match(schema, /activeTripId\s+String\?/);
assert.match(schema, /operatingArea\s+String\?/);
assert.match(destinations, /getCurrentUser\(\)/);
assert.match(destinations, /listActiveDestinations\(db\)/);
assert.doesNotMatch(destinations, /export async function (POST|PUT|PATCH|DELETE)/);
assert.match(trips, /createTripRequest\(db, user\.id/);
assert.doesNotMatch(services, /meetingArea\.length < 2/);
assert.match(services, /meetingArea: input\.meetingArea \|\| null/);
assert.match(services, /destination\.durationOptions\.includes\(input\.requestedDuration\)/);
assert.match(services, /viewerNote\.length > 240/);
assert.match(services, /isolationLevel: Prisma\.TransactionIsolationLevel\.Serializable/);
assert.match(services, /tx\.user\.findUnique/);
assert.match(services, /participant\.role !== Role\.VIEWER/);
assert.match(settings, /user\.role !== Role\.OPERATOR/);
assert.match(settings, /updateOperatorSettings\(db, user\.id/);
assert.match(services, /pendingOfferTripId: null/);
assert.match(services, /activeTripId: null/);
assert.match(services, /data: \{ online: false \}/);
assert.match(services, /city: \{ equals: input\.operatingArea, mode: "insensitive" \}/);
assert.match(online, /evaluateOperatorReadiness/);
assert.match(online, /pendingOfferTripId: null/);
assert.match(online, /activeTripId: null/);
assert.match(marketplace, /equals: trip\.operatingArea/);
assert.match(marketplace, /data: \{ pendingOfferTripId: trip\.id \}/);
assert.match(marketplace, /if \(reserved\.count !== 1\) continue/);
assert.match(marketplace, /if \(claimed\.count !== 1\)/);
assert.match(marketplace, /await tx\.tripOffer\.create/);
assert.match(offers, /getCurrentOffer\(tx, user\.id\)/);
assert.match(accept, /acceptTripOffer\(db, user\.id/);
assert.match(decline, /declineTripOffer\(db, user\.id/);
assert.match(cancel, /cancelTrip\(db, user\.id, user\.role/);
assert.match(end, /endTrip\(db, user\.id, user\.role/);
assert.match(services, /offerExpiresAt: \{ gt: now \}/);
assert.match(services, /pendingOfferTripId: tripId/);
assert.match(services, /activeTripId: tripId/);
assert.match(services, /error\.code === "P2034"/);
assert.match(services, /status: OfferStatus\.DECLINED/);
assert.match(services, /assignNextOperator\(tx, tripId, now\)/);
assert.match(services, /activeTripId: tripId/);
assert.match(viewer, /Request this visit/);
assert.match(operator, /Immediate visit offer/);
assert.match(operator, /offerAction \|\| offerSeconds <= 0/);
assert.doesNotMatch(operator, /status=REQUESTED/);
assert.match(room, /canPublishCamera/);
assert.match(room, /const \{ chatMessages, send, isSending \} = useChat\(\)/);
assert.match(room, /grid-cols-3/);

console.log("Phase 3 focused assertions passed.");
